### PR TITLE
Remove hardcoded references to branch in provision playbooks

### LINKED ISSUE #5509: Remove hardcoded references to branch in provision playbooks for E2E tests
## Description

The E2E vulnerability detection tests currently use playbooks from the QA repository to provision the environment. However, these playbooks are inherited from the Wazuh Ansible repository and include hardcoded versions, making the repository difficult to maintain. More information can be found in this [discussion](https://github.com/wazuh/wazuh-qa/pull/5499#discussion_r1644645097).

To address this issue, it has been proposed to remove these hardcoded references, adapt the Ansible playbook modules to our needs, and update the provisioning modules in the Jenkins libraries accordingly.

## Tasks
- [x] Remove any hardcoded references in the provision modules in the QA repository
- [x] Include necessary parameters in Jenkins pipelines to replace hardcoded values

## Validation

- [x] Ensure E2E vulnerability detection tests are provisioned and run correctly after removing hardcoded references.

### PR DESCRIPTION
**Pull request by santipadilla**
### Closing/Related Issue

Closes #5509

### Description

Removal of the hardcoded references to branch in provision playbooks for E2E tests.

## Tasks
- [x] Remove any hardcoded references in the provision modules in the QA repository

### CODE REVIEW

**Comment by Rebits** [comment]
There are still hardcoded references in the QA provisioning methods:
https://github.com/wazuh/wazuh-qa/blob/f391ccb55b57b43d09876db9b8166c4f7a3fa025/provisioning/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L3

Please review all hardcoded references and implement one of the following approaches:

- Remove unnecessary repository installation tasks that rely on variables with default hardcoded versions (since the E2E pipeline exclusively uses custom packages).
- Replace hardcoded versions with a new parameter.

**Review by Rebits — CHANGES_REQUESTED** [review]
There are still hardcoded references in the QA provisioning methods:
https://github.com/wazuh/wazuh-qa/blob/f391ccb55b57b43d09876db9b8166c4f7a3fa025/provisioning/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L3

Please review all hardcoded references and implement one of the following approaches:

- Remove unnecessary repository installation tasks that rely on variables with default hardcoded versions (since the E2E pipeline exclusively uses custom packages).
- Replace hardcoded versions with a new parameter.

**Review by Rebits — APPROVED** [review]
LGTM

**Review by juliamagan — APPROVED** [review]
LGTM

**Pull request merged**
