### PR TITLE
Add tests for option file_limit

### LINKED ISSUE #646: Syscheck automated tests: Test file_limit option
| Related issue              |
|----------------------|
| wazuh/wazuh#4687  |

## Description

Add tests for new option: `file_limit`. It should work on both manager and agent.

The test must check:
* Only positive values are allowed
```
(1235): Invalid value for element 'file_limit': -10.
```
* Disable `file_limit`
```
(6343): No limit set to maximum number of files to be monitored
```
* `file_limit` set to default: 100000
```
(6342): Maximum number of files to be monitored: '100000'
```
* `file_limit` set to:
    * 1
    * 10
    * 100
    * 1000
```
(6342): Maximum number of files to be monitored: '1000'
```
* Alert for 80% of capacity (_scheduled_)
```
(6039): Sending DB 80% full alert.
```
* Alert for 90% of capacity (_scheduled_)
```
(6039): Sending DB 90% full alert.
```
* Alert for full database
```
(6041): Sending DB 100% full alert.
```
* Alert for returning to <80% of capacity (_scheduled_)
```
(6038): Sending DB back to normal alert.
```

## Platforms
* Linux
* macOS
* Windows

### PR DESCRIPTION
**Pull request by jesusjimsa**
## Description

This PR closes #646. Added tests for new option: `file_limit`. It works on both manager and agent.

The tests check:
* Only positive values are allowed
* Disable `file_limit`
* `file_limit` set to default: 100000
* `file_limit` set to:
    * 1
    * 10
    * 100
    * 1000
* Alert for 80% of capacity (_scheduled_)
* Alert for 90% of capacity (_scheduled_)
* Alert for full database
* Alert for returning to <80% of capacity (_scheduled_)

## Platforms
* Linux
* macOS
* Windows

### CODE REVIEW

**Comment by jesusjimsa** [comment]
## Linux results
```
================================= test session starts =================================
platform linux -- Python 3.6.8, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/vagrant/qa/tests/integration, inifile: pytest.ini
plugins: metadata-1.8.0, html-2.0.1, testinfra-5.0.0
collected 27 items

test_fim/test_file_limit/test_file_limit_capacity_alerts.py ...                 [ 11%]
test_fim/test_file_limit/test_file_limit_default.py ...                         [ 22%]
test_fim/test_file_limit/test_file_limit_full.py ...                            [ 33%]
test_fim/test_file_limit/test_file_limit_no_limit.py ...                        [ 44%]
test_fim/test_file_limit/test_file_limit_values.py ...............              [100%]

============================ 27 passed in 87.36s (0:01:27) ============================
```

**Comment by jesusjimsa** [comment]
## macOS results
```
================================= test session starts =================================
platform darwin -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/vagrant/qa/tests/integration, inifile: pytest.ini
plugins: html-2.0.1, metadata-1.8.0, testinfra-5.0.0
collected 11 items

test_fim/test_file_limit/test_file_limit_capacity_alerts.py ...                 [ 27%]
test_fim/test_file_limit/test_file_limit_default.py .                           [ 36%]
test_fim/test_file_limit/test_file_limit_full.py .                              [ 45%]
test_fim/test_file_limit/test_file_limit_no_limit.py .                          [ 54%]
test_fim/test_file_limit/test_file_limit_values.py .....                        [100%]

================================= 11 passed in 19.19s =================================
```

**Comment by jotacarma90** [comment]
## Windows results
79103825-9866c280-7d6d-11ea-8021-4480b508b7fc

**Comment by jesusjimsa** [comment]
## New Linux results

```
================================ test session starts =================================
platform linux -- Python 3.6.8, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/vagrant/qa/tests/integration, inifile: pytest.ini
plugins: metadata-1.8.0, html-2.0.1, testinfra-5.0.0
collected 24 items

test_file_limit/test_file_limit_capacity_alerts.py ...                         [ 12%]
test_file_limit/test_file_limit_default.py ...                                 [ 25%]
test_file_limit/test_file_limit_full.py ...                                    [ 37%]
test_file_limit/test_file_limit_no_limit.py ...                                [ 50%]
test_file_limit/test_file_limit_values.py ............                         [100%]

=========================== 24 passed in 130.75s (0:02:10) ===========================
```

**Pull request merged**
