### PR TITLE
Replacing custom NVD feed because vulnerabilities are not being inserted

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|#1558|

## Description
It was found that the `test_general_settings/test_general_settings_run_on_start` test fails if it is run isolated. 
It is because the vulnerability detector module can not find any entry in the NVD database and the scan is aborted

```
ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
``` 
This PR replaces the `rest_general_settings/data/feeds/custom_nvd_feed.json` file with `test_vulnerability_detector/test_scan_results/data/custom_nvd_feed.json`. This valid JSON feed is successfully parsed, and the scan finishes as expected with the log:
```
Vulnerability scan finished
```

## Configuration options

The `etc/local_internal_options.conf` file

```
wazuh_modules.debug=2
monitord.rotate_log=0
```

Also, the modules `sca`, `syscollector` and `rootcheck` were disabled.

## Logs example
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [test_general_settings_run_on_start_modules_off_new_nvd_1.log](https://github.com/wazuh/wazuh-qa/files/6816639/test_general_settings_run_on_start_modules_off_new_nvd_1.log) | 2021-07-14| Matias | :green_circle:
| [test_general_settings_run_on_start_modules_off_new_nvd_2.log](https://github.com/wazuh/wazuh-qa/files/6816637/test_general_settings_run_on_start_modules_off_new_nvd_2.log) | 2021-07-14| Matias | :green_circle:
 |[test_general_settings_run_on_start_modules_off_new_nvd_3.log](https://github.com/wazuh/wazuh-qa/files/6816636/test_general_settings_run_on_start_modules_off_new_nvd_3.log) | 2021-07-14| Matias | :green_circle:

## Tests

- [x] Proven that tests **pass** when they have to pass.

### CODE REVIEW

**Comment by mdengra** [comment]
### 2021-07-15

Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_run_on_start_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6821685/test_general_settings_run_on_start_local_r1.log)| 2021-07-15 | Miguel | :red_circle: 
|[test_general_settings_run_on_start_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6821688/test_general_settings_run_on_start_local_r2.log)| 2021-07-15 | Miguel | :red_circle: 
|[test_general_settings_run_on_start_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6821691/test_general_settings_run_on_start_local_r3.log)| 2021-07-15 | Miguel | :red_circle:

**Review by mdengra — CHANGES_REQUESTED** [review]
Hi Matias, unfortunately, when running the test in my testing environment, it fails in one use case. I have attached in a comment the results obtained.

**Comment by damarisg** [comment]
Results when disabling modules: `sca`, `syscollector` and `rootcheck`.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [Results3_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6822780/Results3_RunOnStart.log) | 2021-07-15 | Seyla| :red_circle: 

I executed one time, and It failed. Could Mati run again it? In case, that you can't reproduce we will coordinate to see what differences are there.

**Review by damarisg — CHANGES_REQUESTED** [review]
Results when disabling modules: `sca`, `syscollector` and `rootcheck`.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [Results_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6822780/Results3_RunOnStart.log) | 2021-07-15 | Seyla| :red_circle: 

I executed one time, and It failed. Could Mati run again it? In case, that you can't reproduce we will coordinate to see what differences are there.

**Comment by pereyra-m** [comment]
# Update

This branch was tested again, but this time with the following script to be sure the environment is totally clean for every test.
Basically, it installs Wazuh, sets the `local_internal_options`, disables the unnecessary modules, gets a clean backup of the **wazuh-qa** repository and runs the test three times

```

#!/bin/bash

WAZUH_MANAGER="/home/vagrant/wazuh-manager-4.2.0-1.1493.x86_64.rpm"
TEST_PATH="/home/vagrant/wazuh-qa/tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_run_on_start.py"
OUTPUT_PATH="/home/vagrant/logs/test_general_settings_run_on_start_modules_off_clean"

for i in {1..3}
do
   systemctl stop wazuh-manager
   yum remove wazuh-manager -y
   rm -rf /var/ossec
   yum install $WAZUH_MANAGER -y
   echo "wazuh_modules.debug=2" >> /var/ossec/etc/local_internal_options.conf
   echo "monitord.rotate_log=0" >> /var/ossec/etc/local_internal_options.conf
   if [ -f "/home/vagrant/new_config" ]; then
     cat /home/vagrant/new_config > /var/ossec/etc/ossec.conf
   fi
   systemctl restart wazuh-manager
   if [ -d "/home/vagrant/wazuh-qa-backup" ]; then
     rm -rf /home/vagrant/wazuh-qa
     cp -r /home/vagrant/wazuh-qa-backup /home/vagrant/wazuh-qa
   fi
  
   echo "Running test $i"
   
   python3 -m pytest -vvx $TEST_PATH >> ${OUTPUT_PATH}_${i}.log
   cp /var/ossec/logs/ossec.log /home/vagrant/logs/log_${i}
   
done
```

The test failed every time.

## Analysis

If we compare the old **custom_nvd_feed.json** with the new one, we can see that the first commit sets a new structure for the file. Here we have a snippet 

```
...
"CVE_data_timestamp": "2020-05-21T07:00Z",
  "CVE_Items": [
    {
      "cve": {
        "data_type": "CVE",
...
```
```
....
"CVE_data_timestamp" : "2020-05-21T07:00Z",
  "CVE_Items" : [ {
    "cve" : {
      "data_type" : "CVE",
....
```

This is necessary, because the NVD json parser in vulnerability detector depends heavily on special characters (see [wm_vuldet_json_nvd_parser()](https://github.com/wazuh/wazuh/blob/58b85c551096100e849f3d6ee1fa3876ed4a4010/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1034) method).
 For example

```
    const char * match_cve = " {\r\n    \"cve\" : {\r\n";
```

While debugging the **modulesd** daemon, it was possible to verify that no CVE was being parsed nor inserted, making the test fail when it is run isolated. Consider also that this test only needs to verify the correct scan start-end after a restart, the real information in the feed is irrelevant. At least one valid CVE inserted will avoid the scan abort.

## Fix

Now this second commits copies the exactly same data than before, but with the **cp** command.
The first time, the special characters may have been removed making the parsing fail.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_run_on_start_modules_off_clean_1.log](https://github.com/wazuh/wazuh-qa/files/6826750/test_general_settings_run_on_start_modules_off_clean_1.log)| 2021-07-15| Matias | :green_circle:
| [test_general_settings_run_on_start_modules_off_clean_2.log](https://github.com/wazuh/wazuh-qa/files/6826749/test_general_settings_run_on_start_modules_off_clean_2.log)| 2021-07-15| Matias | :green_circle:
| [test_general_settings_run_on_start_modules_off_clean_3.log](https://github.com/wazuh/wazuh-qa/files/6826748/test_general_settings_run_on_start_modules_off_clean_3.log)| 2021-07-15| Matias | :green_circle:

**Comment by mdengra** [comment]
### 2021-07-16

Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_run_on_start_local_dm_r1.log](https://github.com/wazuh/wazuh-qa/files/6828616/test_general_settings_run_on_start_local_dm_r1.log)| 2021-07-16 | Miguel | :yellow_circle: 
|[test_general_settings_run_on_start_local_dm_r2.log](https://github.com/wazuh/wazuh-qa/files/6828618/test_general_settings_run_on_start_local_dm_r2.log)| 2021-07-16 | Miguel | :yellow_circle: 
|[test_general_settings_run_on_start_local_dm_r3.log](https://github.com/wazuh/wazuh-qa/files/6828619/test_general_settings_run_on_start_local_dm_r3.log)| 2021-07-16 | Miguel | :yellow_circle:

**Review by mdengra — APPROVED** [review]
Great job!

**Review by damarisg — COMMENTED** [review]
Results when disabling modules: `sca`, `syscollector` and `rootcheck`.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [Results_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6830797/Results1StarOnRun.log) | 2021-07-16 | Seyla| 🟡  
| [Results_RunOnStart2.log](https://github.com/wazuh/wazuh-qa/files/6830795/Results2StarOnRun.log) | 2021-07-16 | Seyla| 🟡  
| [Results_RunOnStart3.log](https://github.com/wazuh/wazuh-qa/files/6830796/Results3StarOnRun.log) | 2021-07-16 | Seyla| 🟡

**Review by damarisg — APPROVED** [review]

**Pull request merged**
