### PR TITLE
Fix reliability tests regex statements

### LINKED ISSUE #26100: Review and fix cluster reliability tests
# Description

This issue continues the analysis at https://github.com/wazuh/wazuh/issues/25942 initially opened for `4.9.1`. Since the errors shown were not due to the misbehavior of the cluster but from a bug in the `test_cluster_sync.py` test, it was decided that the necessary changes should be made in the next opened release.

### PR DESCRIPTION
**Pull request by RamosFe**
# Description

Fix `test_cluster_sync.py` regex statements related to logs.

---

### CODE REVIEW

**Review by GGP1 — CHANGES_REQUESTED** [review]
This change looks good to me. However, there is one test (`test_cluster_connection.py`) that will fail sporadically if we don't change it.

I think we should use keep alive messages to validate the nodes connections instead of the first connection message, which can be trimmed from the logs if there are too many messages.

**Comment by RamosFe** [comment]
After implementing the changes suggested by @GGP1, the test passed without any errors:

```console
python3 -m pytest ./test_cluster --artifacts_path /Users/framos/Downloads/artifacts --html=report.html
=========================================================================== test session starts ============================================================================
platform darwin -- Python 3.9.6, pytest-7.1.2, pluggy-0.13.1
rootdir: /Users/framos/Documents/Wazuh/Repositories/wazuh-qa/tests, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-2.0.4
collected 6 items                                                                                                                                                          

test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py .                                                                                  [ 16%]
test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py .                                                                                  [ 33%]
test_cluster/test_cluster_logs/test_cluster_master_logs_order/test_cluster_master_logs_order.py .                                                                    [ 50%]
test_cluster/test_cluster_logs/test_cluster_sync/test_cluster_sync.py .                                                                                              [ 66%]
test_cluster/test_cluster_logs/test_cluster_task_order/test_cluster_task_order.py .                                                                                  [ 83%]
test_cluster/test_cluster_logs/test_cluster_worker_logs_order/test_cluster_worker_logs_order.py .                                                                    [100%]

------------------------------ generated html file: file:///Users/framos/Documents/Wazuh/Repositories/wazuh-qa/tests/reliability/report.html -------------------------------
============================================================================ 6 passed in 28.85s ============================================================================
```

**Review by GGP1 — DISMISSED** [review]
LGTM

**Review by GGP1 — CHANGES_REQUESTED** [review]
The issue release is `4.10.1` but the PR points to master, the branch corresponding to the target release version does not exist yet (it does [exist](https://github.com/wazuh/wazuh/tree/4.10.1) in wazuh/wazuh), so we should wait until it is created to proceed.

This is to avoid the scenario in which the branch is created before the PR is merged and the change is not applied.

**Review by fdalmaup — APPROVED** [review]

**Review by GGP1 — APPROVED** [review]
LGTM

**Review by fdalmaup — APPROVED** [review]

**Review by juliamagan — APPROVED** [review]

**Pull request merged**
