### PR TITLE
Support IPv6 tests

### LINKED ISSUE #2224: Support IPv6 for agents
## Description

This issue is associated with https://github.com/wazuh/wazuh/issues/4243. The goal of this set of issues is to investigate, design, and create automatic tests for the IPv6 support.

## Tasks

- #2225
- Development I: Adapt existing tests:
  - #2252
  - #2253 
  - #2257 
- Development II: Design and create new tests:
  - #2254 
  - #2284 
  - #2266

### PR DESCRIPTION
**Pull request by juliamagan**
closes #2224

## Description

In this branch, we can find all the development made for the IPv6 support, according to https://github.com/wazuh/wazuh/issues/4243

**Issues**
- #2343
- #2254
- #2252 
- #2253 
- #2363 
- #2372
- #2373 
- #2374 
- #2375 
- #2385 
- #2394 
- #2396 
- #2284 
- #2266 
- #2403 

**Merged PRs**
- #2348
- #2288
- #2265
- #2270
- #2404
- #2341
- #2439

### CODE REVIEW

**Comment by Rebits** [comment]
#2255 development will be implemented in the future

**Comment by juliamagan** [comment]
## 29/12/2021

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-dev.support.ipv6.msi


### Integration Tests

**test_active_response**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 | 
***
**test_authd**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 | 
***
**test_enrollment**

|CentOS Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 | 

|Windows Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 | 
***
**test_remoted**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 |

**Comment by juliamagan** [comment]
## 02/02/2022

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-dev.support.ipv6.msi


### Integration Tests

**test_authd**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1|🔵| [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/19818/)
|R2 | 🔵 | 
|R3 | 🔵  |
***


- :green_circle:: All pass
- :yellow_circle:: Some warnings
- 🟠 : Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 08/02/2022

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-dev.support.ipv6.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-dev.support.ipv6.msi


### Integration Tests

**test_active_response**

|CentOS Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 || 
|R3 | | 

|Windows Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 || 
|R3 ||  
***
**test_authd**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 ||
***
**test_enrollment**

|CentOS Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| |
|R2 | |
|R3 | | 

|Windows Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| | 
|R2 | |
|R3 |  |
***
**test_remoted**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1|   | 
|R2 | | 
|R3 |  | 

***


- :green_circle:: All pass
- :yellow_circle:: Some warnings
- 🟠 : Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
Regarding [remoted results](https://github.com/wazuh/wazuh-qa/pull/2435#issuecomment-1032613906), the following test cases fails:

- `test_shared_configuration[TCP]`: It seems that the time taken to send the shared configuration has increased causing this failure locally. We should study how much is this increase and if it is reasonable to increase the timeout.

- `test_basic_configuration_queue_size_too_big.py::test_big_queue_size[('secure', '1514', '99999999')]` and `test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,Testing_syslog_514]`: These failed cases may be related to the increase of time required to up remoted with invalid configuration. It is required:
   - Add a fixture to wait all daemons until API calls.
   - Research if the increase of timeout is reasonable and adjust global remoted parameters accordingly.

**Comment by Rebits** [comment]
## 11/02/222

After applying https://github.com/wazuh/wazuh-qa/pull/2557 fix, ipv6 system tests seem to work correctly.
### Branch
`dev-support-ipv6`

## Testing

### `test_agent_auth`
|  Round | Result |
|---|---|
| R1   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048497/R5-IPV6-AGENT-AUTH.tar.gz) |
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048499/R6-IPV6-AGENT-AUTH.tar.gz) |
| R3   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048501/R7-IPV6-AGENT-AUTH.tar.gz) |
| R4   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048501/R7-IPV6-AGENT-AUTH.tar.gz) |
| R5   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048503/R8-IPV6-AGENT-AUTH.tar.gz) |
| R6   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048505/R9-IPV6-AGENT-AUTH.tar.gz) |
| R7   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048507/R10-IPV6-AGENT-AUTH.tar.gz) |

### `test_enrollment`
|  Round | Result |
|---|---|
| R1   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048500/R6-IPV6-ENROLLMENT.tar.gz) |
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048502/R7-IPV6-ENROLLMENT.tar.gz) |
| R3   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048504/R8-IPV6-ENROLLMENT.tar.gz) |
| R4   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048506/R9-IPV6-ENROLLMENT.tar.gz) |
| R5   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048508/R10-IPV6-ENROLLMENT.tar.gz) |
| R6   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048531/R2-IPV6-ENROLLMENT.tar.gz) |
| R7   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8048532/R3-IPV6-ENROLLMENT.tar.gz) |



* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
## 21/02/2022 

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit0abb7e3.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit0abb7e3.x86_64.rpm
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/windows/wazuh-agent-4.4.0-0.commit0abb7e3.msi

### Integration Tests

**test_active_response**

|CentOS Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:  | :large_blue_circle:  |
R2 | :large_blue_circle:  | :large_blue_circle:  |
R3 | :large_blue_circle:  | :large_blue_circle:  |

|Windows Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:   | :large_blue_circle:  |
R2 | :large_blue_circle:  | :large_blue_circle:  |
R3 | :large_blue_circle:  | :large_blue_circle: |
***

**test_authd**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:   | :large_blue_circle:  |
R2 | :large_blue_circle:  | :large_blue_circle:  |
R3 | :large_blue_circle:  | :large_blue_circle: |
***

**test_enrollment**

|CentOS Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:   | :large_blue_circle:  |
R2 | :large_blue_circle:  | :large_blue_circle:  |
R3 | :large_blue_circle:  | :large_blue_circle: |
***

|Windows Agent| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:   | :large_blue_circle:  |
R2 | :large_blue_circle:  | :large_blue_circle:  |
R3 | :large_blue_circle:  | :large_blue_circle: |


***
**test_remoted**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
R1 | :large_blue_circle:   | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/21448/console)   |
R2 | :large_blue_circle:  | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/21449/console) |
R3 | :large_blue_circle:  | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/21450/console) |
***

***


- :green_circle:: All pass
- :yellow_circle:: Some warnings
- 🟠 : Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
### 23/02/2022

### Branch

`dev-support-ipv6`

### `test_enrollment`

Round | Result
-- | --
R1 |  [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8123589/R1-enrollment.zip)
R2 |  [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8123590/R2-enrollment.zip)
R3 |  [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8123591/R3-enrollment.zip)

**Comment by Rebits** [comment]
### 25/02/022

ACK test https://github.com/wazuh/wazuh-qa/issues/2364 development is going to be merged in future interactions when https://github.com/wazuh/wazuh/issues/11614 is done.

**Comment by Rebits** [comment]
### 25/02/022

The possible error in the QA framework is not exclusive to these system tests. For this reason, the research is going to be tracked in this issue https://github.com/wazuh/wazuh-qa/issues/2609

Taking this into account this development is moved to Review Approve

**Comment by Rebits** [comment]
### 01/03/2022
### Branch

`dev-support-ipv6`

### `test_enrollment`

Round | Result
| --- | --- |
| R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161005/R1-enrollment.zip) |
R2 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161006/R2-enrollment.zip)
R3 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161007/R3-enrollment.zip)
R4 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161008/R4-enrollment.zip)
R5 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161009/R5-enrollment.zip)
R6 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161010/R6-enrollment.zip)
R7 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161011/R7-enrollment.zip)
R8 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161012/R8-enrollment.zip)
R9 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161013/R9-enrollment.zip)
R10 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8161014/R10-enrollment.zip)



### `test_agent_authd`

Round | Result
-- | --
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160982/R1-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160983/R2-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160984/R3-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160985/R4-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160986/R5-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160987/R6-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160988/R7-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160989/R8-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160990/R9-agent-auth.zip)
R1 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8160991/R10-agent-auth.zip)

**Review by Rebits — APPROVED** [review]
LGTM

**Pull request merged**
