### PR TITLE
Fix logic for xfail test in api performance test

### LINKED ISSUE #3665: Improve xfailed management in API performance tests
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
| - | https://github.com/wazuh/wazuh/issues/15653 | - |

## Description
Currently, the way xfail is used in API performance tests prevents endpoint execution from even being attempted:
https://github.com/wazuh/wazuh-qa/blob/1333324d33b713631cde7bebfb9a1af63ef20d35/tests/performance/test_api/test_api_endpoints_performance.py#L35-L38

This makes it impossible to determine if any of the listed endpoints have worked correctly:
https://github.com/wazuh/wazuh-qa/blob/1333324d33b713631cde7bebfb9a1af63ef20d35/tests/performance/test_api/test_api_endpoints_performance.py#L15-L22

Sometimes, such as for the `PUT /agents/group` endpoint in the tests run in the issue below, it might be useful to know if it's still failing or not, without explicitly modifying the list:
- https://github.com/wazuh/wazuh/issues/15653

## Considerations
These tests are usually run inside a performance pipeline.

### PR DESCRIPTION
**Pull request by RamosFe**
|Related issue|
|-------------|
|  https://github.com/wazuh/wazuh-qa/issues/3665 |

## Description

Added logic to API Performance test to check if a test case marked as `xfailed` ran correctly.

### CODE REVIEW

**Comment by RamosFe** [comment]
## Update

The changelog wasn't updated because this Issue doesn't have an assigned `Release`.

**Review by GGP1 — CHANGES_REQUESTED** [review]
The changelog should be added to the latest available version if no release is assigned to the issue.

Also, we are requested by QA to include the test logs of three consecutive executions, so please add them to the pull request description.

**Comment by RamosFe** [comment]
## Update

Changed the logic of the test to the endpoints and then marked them as `xfail` if failed. If it does not fail, print a warning.

### Executions Results
[TestRunsTerminal.txt](https://github.com/wazuh/wazuh-qa/files/13453657/TestRunsTerminal.txt)
[Reports.zip](https://github.com/wazuh/wazuh-qa/files/13453659/Reports.zip)

> The changelog wasn't changed in the commits due to the Issue not having a release specified.

**Review by GGP1 — DISMISSED** [review]
LGTM

**Review by Selutario — CHANGES_REQUESTED** [review]
LGTM, add the changelog entry for 4.9.0 (since this is targeting master branch)

**Review by Selutario — CHANGES_REQUESTED** [review]
It seems the QA team updated the changelog and there are some conflicts that need to be fixed before merging.

**Review by Selutario — APPROVED** [review]

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
