### PR TITLE
Fix E2E Vulnerability tests to run in different python versions on yum-dependant OS 

### LINKED ISSUE #5717: centOS packages are not installing correctly in E2E Vulnerability detection for python310
# Description

It was detected in an E2E vulnerability detection tests report (by @QU3B1M) that the centOS packages are not installing correctly in case of running these tests with a 3.10.12, instead of the 3.9 used in the automation pipeline.

Report's logs show these errors:
```
2024-09-04 00:15:59 Error installing package on agent4: expected string or bytes-like object (remote_operations_handler.py:335)
2024-09-04 00:15:59 Error installing package on agent1: expected string or bytes-like object (remote_operations_handler.py:335)
```
Marking the operation_results check as failed
```
E         Check operation_successfull_for_all_agents failed. Evidences (['operation_results']) can be found in the report.
```

# Tasks
- [x] Research installation error using python 3.10.12
- [x] Update the E2E framework to support the installation of CentOS packages across all versions. 

# Validation
- [x] Install with success a centos package using  python 3.10.12

# Evidences
- [report.zip](https://github.com/user-attachments/files/16870145/report.2.zip)

### PR DESCRIPTION
**Pull request by jseg380**
# Description

This PR fixes the error reported in https://github.com/wazuh/wazuh-qa/issues/5717

---

## Testing performed

It was validated that the root cause of the error lies in the version difference of ansible and ansible-core (dependencies on requirements.txt). The ansible `yum` module doesn't seem to work on version 10.4.0 of ansible and 2.17.4 of ansible-core yet it works fine in versions 8.7.0 and 2.15.12 respectively.
In order to fix this the use of the `yum` module has been replaced by the command used to install the package directly, it has proven to work.

After verifying that it works with Python 3.10 it was tested with Python 3.9, the result is also satisfactory:
```
[qa@ip-x-x-x-x ~]$ yum list installed | grep grafana
grafana.x86_64                          8.5.6-1                       @/grafana-8.5.6-1.x86_64
```

### CODE REVIEW

**Review by rafabailon — DISMISSED** [review]
LGTM

**Review by Rebits — APPROVED** [review]
LGTM

**Review by Rebits — CHANGES_REQUESTED** [review]
Include the changelog

**Review by Rebits — DISMISSED** [review]
LGTM

**Review by Rebits — APPROVED** [review]

**Pull request merged**
