### PR TITLE
Solve Problems with WPK - Update README.md 

### PR DESCRIPTION
**Pull request by damarisg**
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/1898|

## Description
I detected methods deleted. Also that the test failed because some paths were hardcoded. For that reason, I applied new changes and also modified README.md because it was required.

## Packages Details 

Details of branch after to apply merged with package used it. 

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 4.2 | https://github.com/wazuh/wazuh-qa/commit/c6981d83a644cd9fe9b2644680ae26e4bd5ea217 |v4.2.2-rc1 |https://github.com/wazuh/wazuh/commit/411389188f449c3e7a2d97ff059c25035d32f38a |

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-manager-4.2.2-1.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.2 | 40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.msi|

We are going to check that after to add this method all wpk tests work successfully. 

### local_internal_options.conf

<table>
 <tr>
  <td rowspan="2">WPK</td>
  <td>(Manager, Agent) - Linux</td>
  <td>wazuh_modules.debug=2</td>
    <td>--wpk_version=v4.x.x  --wpk_package_path="packages-dev.wazuh.com/pre-release/wpk/"</td>
 </tr>
  <td>Agent - Windows</td>
  <td>windows.debug=2</td>
  <td>--wpk_version=v4.x.x  --wpk_package_path="packages-dev.wazuh.com/pre-release/wpk/"</td>
 </tr>

</table>

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | "gusztavvargadr/windows-10" | Windows | 2 | 2048 |
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

## Logs example

To run it now, you need to add the package path. I attach a sample: 

> python3 -m pytest -svx test_wpk/ >  /vagrant/ResutsWpk.log --wpk_version=v4.2.2 --wpk_package_path="packages-dev.wazuh.com/pre-release/wpk/"

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

### CODE REVIEW

**Comment by danisan90** [comment]
### test_wpk
These are the results of the execution of `test_wpk` in the branch `1898-wpk-fixed-and-new-args-for-the-execution` 
| Results | Date | By | Status |
|:--:|:--:|:--:|:--:|

**Review by danisan90 — APPROVED** [review]
Test results in this [comment.](https://github.com/wazuh/wazuh-qa/pull/1928/#issuecomment-926639044).

**Comment by Deblintrake09** [comment]
### test_wpk
These are the results of the execution of `test_wpk` in the branch `1898-wpk-fixed-and-new-args-for-the-execution` in Linux.
|Type| Results | Date | By | Status |
|:--:|:--:|:--:|:--:|:--:|
| Manager | [ResultsWPK-Manager.zip](https://github.com/wazuh/wazuh-qa/files/7235905/ResultsWPK-Manager.zip) | 2021/09/23| @Deblintrake09  | 🟢
| Manager | [ResutsWpk-Manager2.log](https://github.com/wazuh/wazuh-qa/files/7235907/ResutsWpk.log) | 2021/09/24| @Deblintrake09  | 🟢 
| Manager | [ResultsWPK-Manager3.zip](https://github.com/wazuh/wazuh-qa/files/7235906/ResultsWPK-Manager3.zip) | 2021/09/24| @Deblintrake09  | 🟢 |
| Linux Agent |[ResultsWPK-LinuxAgent.zip](https://github.com/wazuh/wazuh-qa/files/7235904/ResultsWPK-LinuxAgent.zip) | 2021/09/24| @Deblintrake09  | :green_circle: 

Tests for Windows Agent were not launched - Does not recognize the new parameters. Screenshot added.
WPK Windows
eters.

**Comment by damarisg** [comment]
Results After to fix windows problems. 
| Results | Date | By|  Status
|--|--|--|--|
[ResultsWpkWindows.zip](https://github.com/wazuh/wazuh-qa/files/7243436/ResultsWpkWindows.zip)| 2021/09/28 | Seyla | 🟢 
[ResultsWpkWindows.zip](https://github.com/wazuh/wazuh-qa/files/7243435/ResultsWpkWindows2.zip)| 2021/09/28 | Seyla | 🟢 
[ResultsWpkWindows.zip](https://github.com/wazuh/wazuh-qa/files/7243428/ResultsWpkWindows.zip) | 2021/09/28 | Seyla | 🟢

**Review by Deblintrake09 — APPROVED** [review]
Run 3 test instances :green_circle:

**Comment by snaow** [comment]
LGTM

**Pull request merged**
