### PR TITLE
Tests VD - Fix failures related to `mock_agent` scope

### PR DESCRIPTION
**Pull request by damarisg**
|Related issue|
|---|
| https://github.com/wazuh/wazuh-qa/issues/2092|

## Description

Disable this test like 4.2 because it requires a refactor when it manages the DataBase.

## local_internal_option.conf

> wazuh_modules.debug=2
> monitord.rotate_log=0 

## Logs 

| Test Path | Status | Type |  Date | By 
|--|--|--|--|--|
test_vulnerability_detector/ | [🟢](https://ci.wazuh.info/view/Tests/job/Test_integration/14761/) | Jenkins | 2021/11/01 | Seyla
test_vulnerability_detector/ | [🟢](https://ci.wazuh.info/view/Tests/job/Test_integration/14760/) | Jenkins | 2021/11/01 | Seyla
test_vulnerability_detector/ | [🟢](https://ci.wazuh.info/view/Tests/job/Test_integration/14759/) | Jenkins | 2021/11/01 | Seyla

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

### CODE REVIEW

**Comment by juliamagan** [comment]
## 29/10/2021
### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-qa.vr.1473.x86_64.rpm


## Testing

These tests were tested in `1248-amazon-linux-vuln` branch

### tests/integration/test_vulnerability_detector

|  OS  | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| PS1   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7448475/PS1-1473-centos-manager.tar.gz)  | [🟡 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14667/)    |
| PS2   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7448476/PS2-1473-centos-manager.tar.gz) |   [🟡 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14668/)  | |
| PS3   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7448479/PS3-1473-centos-manager.tar.gz) |    [🟡 ](https://ci.wazuh.info/view/Tests/job/Test_integration/14669/)  | |


* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 03/11/2021
### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|


## Testing

### tests/integration/test_vulnerability_detector

|  OS  | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| PS1   | |    |
| PS2   | |   | |
| PS3   |  |    | |


* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
## 08/11/2021
After talking with @MarcelKemp, the error present in centos7 systems seems to be related to an error in `mock_system` fixture. This was not updating VD last scan metadata, so adding a `update_last_scan` should fix this issue.

**Comment by Rebits** [comment]
## 10/11/2021
### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|


## Testing

### tests/integration/test_vulnerability_detector

|  OS  | Jenkins   | Local     | Notes
|---    |---    |---    |---    |
| PS1   | [:green_circle:](https://ci.wazuh.info/job/Test_integration/15546/consoleFull) |  :red_circle:   |
| PS2   | [:green_circle: ](https://ci.wazuh.info/job/Test_integration/15545/console) | :red_circle:  | |
| PS3   | [:green_circle: ](https://ci.wazuh.info/job/Test_integration/15545/console) | :red_circle:  ||


Local false positives are related to errors in test_feeds, produces by connection errors for poor internet connection.

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 11/11/2021
### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|40301|https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.0-2160.vd.green.x86_64.rpm


## Testing

### tests/integration/test_vulnerability_detector

|  OS  | Jenkins   |  Notes
|---    |---    |---    |
| PS1   | [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/15829/)  |
| PS2  |  [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/15830/) | |
| PS3   |  [🔵 ](https://ci.wazuh.info/view/Tests/job/Test_integration/15831/)  ||




* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
The tests don't pass in local environments. They will be fixed in https://github.com/wazuh/wazuh-qa/issues/2178.

**Pull request merged**
