### PR TITLE
Remove FIM hard link tests

### LINKED ISSUE #1475: Update 'hard_link' integration test
Hello team,
I open this issue to update the integration tests related to the hard links, due to some recent changes in the database, we have stopped supporting them in the alerts, so the `hard_link` field has been removed.
Here issues related to these changes in DB:
https://github.com/wazuh/wazuh/issues/8825

I have also noticed that only the tests are executed with the scheduled mode, so it would be a good opportunity to rethink it.

Best regards!

### PR DESCRIPTION
**Pull request by Molter73**
|Related issue|
|---|
|#1475|

## Description

This PR removes tests associated with hardlinks on FIM. This change is due to the fact that FIM will no longer track hardlinks so the tests themselves are no longer needed. This PR closes #1475 and is also associated with wazuh/wazuh#8825

## Tests

- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.

### CODE REVIEW

**Review by antoniomanuelfr — CHANGES_REQUESTED** [review]
We should also remove the YAML file associated with the test, as it's no longer used
https://github.com/wazuh/wazuh-qa/blob/8825-epic-fim-db-tables-unify/tests/integration/test_fim/test_files/test_checks/data/wazuh_hard_link.yaml

**Review by antoniomanuelfr — APPROVED** [review]
LGTM

**Review by jotacarma90 — APPROVED** [review]
LGTM

**Review by jmv74211 — CHANGES_REQUESTED** [review]
Remove the corresponding test from the `mkdocs.yaml` file as well.

https://github.com/wazuh/wazuh-qa/blob/8825-epic-fim-db-tables-unify/mkdocs.yml#L214

**Review by jmv74211 — APPROVED** [review]

**Review by Rebits — APPROVED** [review]
LGTM

**Review by antoniomanuelfr — APPROVED** [review]

**Pull request merged**
