### PR TITLE
Remoted IPv6 tests

### PR DESCRIPTION
**Pull request by juliamagan**
|Related issue|
|---|
| Closes: #2257|

## Description

In this branch, we can find all the development made for the IPv6 remoted support.

## Issues

- #2363 
- #2372
- #2373
- #2374 
- #2375 
- #2385 
- #2394 
- #2396 

## Merged PRs

- #2378
- #2381 
- #2402
- #2382 
- #2386 
- #2395
- #2397

### CODE REVIEW

**Comment by juliamagan** [comment]
## 11/01/2022

### Packages
| Version | Revision | Link|
|---|---|---|
|v4.4.0|40400|https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm


### Testing
**tests/integration/test_remoted**

|  CentOS Manager | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7853081/R1-2439-centos-manager.tar.gz)  |  | |
| R2   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7853082/R2-2439-centos-manager.tar.gz)  |     | |
| R3   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7853086/R3-2439-centos-manager.tar.gz)  |     | |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 12/01/2022

### Packages
| Version | Revision | Link|
|---|---|---|
|v4.4.0|40400|https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm


### Testing
**tests/integration/test_remoted**

|  CentOS Manager | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   |[🔴 ](https://github.com/wazuh/wazuh-qa/files/7855976/R1-2439-centos-manager.tar.gz)  |  | |
| R2   |[🔴 ](https://github.com/wazuh/wazuh-qa/files/7855981/R2-2439-centos-manager.tar.gz) |     | |
| R3   | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7855985/R3-2439-centos-manager.tar.gz) |     | |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 14/01/2022

### Packages
| Version | Revision | Link|
|---|---|---|
|v4.4.0|40400|https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm


### Testing
**tests/integration/test_remoted**

|  CentOS Manager | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   | 🔵   |  | |
| R2   | 🔵  |     | |
| R3   | 🔵  |     | |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by juliamagan** [comment]
## 17/01/2022

### Packages
| Version | Revision | Link|
|---|---|---|
|v4.4.0|40400|https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-dev.support.ipv6.x86_64.rpm


### Testing
**tests/integration/test_remoted**

|  CentOS Manager | Local   | Jenkins     | Notes
|---    |---    |---    |---    |
| R1   |   | [🔵  ](https://ci.wazuh.info/view/Tests/job/Test_integration/18884/) | |
| R2   | |   | |
| R3   | |  | |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- 🟠 : Jenkins error
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
After increasing timeout for `test_request_agent_info` and `test_shared_configuration`  801c224, full-green has been achieved for local environment

## 01/13/202

| Version | Revision |Link|
|---|---|---|
|`dev-support-ipv6`  | commitb079b98 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commitb079b98.x86_64.rpm

## Testing

### `test_remote`

|  OS | Local  | Jenkins     | Notes
|---    |---   |---    |---    |
| R1 |   [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7924693/PS1-2439-centos-manager-remoted.zip) | [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/19228/)   |
| R2  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7924694/PS2-2439-centos-manager-remoted.zip)  |  [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/19227/)    |
| R3  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7924696/PS3-2439-centos-manager-remoted-timeout.zip) |  [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/19187/)   

* * * 
- :green_circle:: All pass
- :yellow_circle:  Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progess

**Pull request merged**
