### PR TITLE
Increasing timeout for vulnerability detector tests that require many files downloads

### PR DESCRIPTION
**Pull request by pereyra-m**
|Related issue|
|---|
|#1560|

## Description

It was found that the `test_providers/test_providers_multiple_providers` test takes too much time to download the required feeds, and sometime the default timeout isn't enough. The required logs are printed after the test fails.

The timeout for this test was increased with the new **TEST_PROVIDERS_TIMEOUT** to allow the tests to pass in those environments with slower internet connections. 

## Configuration options

As this [comment](https://github.com/wazuh/wazuh-qa/issues/1560#issuecomment-879422818) shows, disabling the unused modules doesn't fix the test, so a problem in the `FileMonitor` class is discarded.

The **TEST_PROVIDERS_TIMEOUT** is set to 120s, but this value could be increased if necessary. 

## Logs example

These are the results with the `1560-multiple-providers` branch

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_multiple_providers_modules_off_timeout_extended_1.log](https://github.com/wazuh/wazuh-qa/files/6818846/test_providers_multiple_providers_modules_off_timeout_extended_1.log)| 2021-07-14| Matias | :green_circle: 
|[test_providers_multiple_providers_modules_off_timeout_extended_2.log](https://github.com/wazuh/wazuh-qa/files/6818845/test_providers_multiple_providers_modules_off_timeout_extended_2.log)| 2021-07-14| Matias | :green_circle: 
| [test_providers_multiple_providers_modules_off_timeout_extended_3.log](https://github.com/wazuh/wazuh-qa/files/6818844/test_providers_multiple_providers_modules_off_timeout_extended_3.log)| 2021-07-14| Matias | :green_circle: 

## Tests

- [x] Proven that tests **pass** when they have to pass.

### CODE REVIEW

**Review by mdengra — APPROVED** [review]
Good work!

**Comment by mdengra** [comment]
### 2021-07-15

Test results with the default modules enabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_multiple_providers_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6821474/test_providers_multiple_providers_local_r1.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_providers_multiple_providers_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6821479/test_providers_multiple_providers_local_r2.log)| 2021-07-15 | Miguel | :yellow_circle: 
|[test_providers_multiple_providers_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6821482/test_providers_multiple_providers_local_r3.log)| 2021-07-15 | Miguel | :yellow_circle:

**Review by damarisg — COMMENTED** [review]
It works! Good Job!
I attach the results when disabling modules: `sca`, `syscollector` and `rootcheck`.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [Results1_multipleProviders.log](https://github.com/wazuh/wazuh-qa/files/6823049/Results1_multipleProviders.log)| 2021-07-15 | Seyla| :yellow_circle: 
|[Results1_multipleProviders2.log](https://github.com/wazuh/wazuh-qa/files/6823050/Results1_multipleProviders2.log)| 2021-07-15 | Seyla| 🟢
| [Results1_multipleProviders3.log](https://github.com/wazuh/wazuh-qa/files/6823048/Results1_multipleProviders3.log)| 2021-07-15 | Seyla| :yellow_circle: 


| Reference | Status | 
|--|--|
| 🟢 | Pass without warnings|
| 🟡 | Pass with Warnings |

**Review by damarisg — APPROVED** [review]

**Comment by pereyra-m** [comment]
# Update

Now there is only one **DOWNLOAD_TIMEOUT** value instead of the sum of two different ones.

It wasn't possible to reduce the total test time configuring the `RedHat` feed from a more recent year (2019 for example), because the tests fail in the `Debian` feed download: this big file is unified and can't be requested by steps.

```
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:452 Event 'Trying to download https://security-tracker.debian.org/tracker/data/json' was not received
ERROR    wazuh_testing:monitoring.py:453 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:455 Results expected: 1
=========================== short test summary info ============================
FAILED wazuh-qa/tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_providers.py::test_multiple_providers[test_debian_default]

```

Also, it is interesting that while testing different many different timeouts values, sometimes the problem is in a local feed, suggesting that maybe the parsing is also slow (and not only the download). Here we have an example

```
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:452 Event 'Trying to download /home/vagrant/wazuh-qa/tests/integration/test_vulnerability_detector/test_providers/../data/feeds/custom_debian_json_feed.json' was not received
ERROR    wazuh_testing:monitoring.py:453 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:455 Results expected: 1
=========================== short test summary info ============================
FAILED wazuh-qa/tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_providers.py::test_multiple_providers[test_debian_multipath]

```

## Conclusion

It isn't possible to reduce the timeout as expected because that needs a more time consuming test rework.
We'll leave the timeout value in the lowest possible value for local tests.
Here are the results for the last commit with **DOWNLOAD_TIMEOUT = 140**, every round takes almost 7 minutes

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_providers_multiple_providers_modules_off_clean_1.log](https://github.com/wazuh/wazuh-qa/files/6830829/test_providers_multiple_providers_modules_off_clean_1.log)| 2021-07-16| Matias | :green_circle:
|[test_providers_multiple_providers_modules_off_clean_2.log](https://github.com/wazuh/wazuh-qa/files/6830828/test_providers_multiple_providers_modules_off_clean_2.log)| 2021-07-16| Matias | :green_circle:
|[test_providers_multiple_providers_modules_off_clean_3.log](https://github.com/wazuh/wazuh-qa/files/6830827/test_providers_multiple_providers_modules_off_clean_3.log) | 2021-07-16| Matias | :green_circle:

**Review by damarisg — COMMENTED** [review]
I understand the point, if this approach is approved by Pedro, we can continue with this, and in the future improve this test.

I attach the results when disabling modules: `sca`, `syscollector` and `rootcheck`.

 
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [ResultsMultipleProvider1.log](https://github.com/wazuh/wazuh-qa/files/6831285/ResultsMultipleProvider1.log)| 2021-07-16 | Seyla| :yellow_circle: 
|[ResultsMultipleProvider2.log](https://github.com/wazuh/wazuh-qa/files/6831286/ResultsMultipleProvider2.log)| 2021-07-16 | Seyla| :yellow_circle: 
| [ResultsMultipleProvider3.log](https://github.com/wazuh/wazuh-qa/files/6831287/ResultsMultipleProvider3.log)| 2021-07-16 | Seyla| :yellow_circle: 


| Reference | Status | 
|--|--|
| 🟡 | Pass with Warnings |

**Review by damarisg — APPROVED** [review]

**Pull request merged**
