### PR TITLE
[DUMMY] Reporting testing PR

### PR DESCRIPTION
**Pull request by Zenidd**
Hi team,

this PR has debugging purposes related to the FIM system tests reporting phase.

Greetings, 
JP Sáez

### CODE REVIEW

**Comment by wazuhci** [comment]
### General
- Scenarios:

**Comment by wazuhci** [comment]
### General
- Scenarios: 
201_default_configuration_frequency
202_realtime_monitoring
203_whodata_frequency
204_whodata_linux_noaudit
205_restrict_option
206_tag_option
207_report_changes_frequency
208_ignore_files
209_recursion_level
210_scheduled_scan

**Comment by wazuhci** [comment]
## FIM System tests
### Tested scenarios: 
- [201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) - Default syscheck configuration
- [202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - Real time monitoring
- [203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - Whodata Linux/Windows
204_whodata_linux_noaudit

**Comment by wazuhci** [comment]
## FIM System tests
### Tested scenarios: 
- [201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) - Default syscheck configuration
- [202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - Real time monitoring
- [203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - Whodata
- [204](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#204---whodata-linux---no-audit-installed-520) - Whodata (no audit)
- [205](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#205---use-of-restrict-option-linuxwindows-526) - Restrict option
- [206](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#206---use-of-tags-linuxwindows-524) - Tags usage
- [207](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#207---use-of--report-changes-linuxwindows-523) - Report changes
- [208](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#208---use-of-ignore-files-linuxwindows-538) - Ignore files
- [209](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#209---recursion-level-540) - Recursion level
- [210](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#210---scheduled-scan-553) - Scheduled scan

**Comment by wazuhci** [comment]
## FIM System tests
- Commit: fdd5ab2
### Tested scenarios: 
- [201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) - Default syscheck configuration
- [202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - Real time monitoring
- [203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - Whodata
- [204](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#204---whodata-linux---no-audit-installed-520) - Whodata (no audit)
- [205](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#205---use-of-restrict-option-linuxwindows-526) - Restrict option
- [206](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#206---use-of-tags-linuxwindows-524) - Tags usage
- [207](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#207---use-of--report-changes-linuxwindows-523) - Report changes
- [208](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#208---use-of-ignore-files-linuxwindows-538) - Ignore files
- [209](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#209---recursion-level-540) - Recursion level
- [210](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#210---scheduled-scan-553) - Scheduled scan

**Comment by Zenidd** [comment]
## Output Sample 0 - Plain text

## FIM System tests
- Commit: [fdd5ab2](commit.commit)
### Tested scenarios: 

- [201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) **- Default syscheck configuration**
    - Redhat 8 - OK
    - Centos 7 - OK
    - Ubuntu 16.04 - OK
    - **Ubuntu 18.04 - NOT OK 
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Ubuntu 14.04 - OK
    - Amazon Linux 2 - OK
    - Windows 2019 - OK
    - **Windows 2016 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Windows 2012 - OK
- [202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - **Real time monitoring**
    - Redhat 8 - OK
    - Centos 7 - OK
    - Ubuntu 16.04 - OK
    - **Ubuntu 18.04 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Ubuntu 14.04 - OK
    - Amazon Linux 2 - OK
    - Windows 2019 - OK
    - **Windows 2016 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Windows 2012 - OK
- [203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - **Whodata**
    - Redhat 8 - OK
    - Centos 7 - OK
    - Ubuntu 16.04 - OK
    - **Ubuntu 18.04 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Ubuntu 14.04 - OK
    - Amazon Linux 2 - OK
    - Windows 2019 - OK
    - **Windows 2016 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Windows 2012 - OK
- [204](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#204---whodata-linux---no-audit-installed-520) - **Whodata (no audit)**
    - Redhat 8 - OK
    - Centos 7 - OK
    - Ubuntu 16.04 - OK
    - **Ubuntu 18.04 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Ubuntu 14.04 - OK
    - Amazon Linux 2 - OK
    - Windows 2019 - OK
    - **Windows 2016 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Windows 2012 - OK
- [205](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#205---use-of-restrict-option-linuxwindows-526) - **Restrict option**
    - Redhat 8 - OK
    - Centos 7 - OK
    - Ubuntu 16.04 - OK
    - **Ubuntu 18.04 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Ubuntu 14.04 - OK
    - Amazon Linux 2 - OK
    - Windows 2019 - OK
    - **Windows 2016 - NOT OK
Alerts verification failed:**
_additions triggered 5000 - received 4500
deletions triggered 5000 - received 4500
modifications triggered 5000 - received 4500_
    - Windows 2012 - OK

**Comment by Zenidd** [comment]
## Output Sample 1 - Plain text with

## FIM System tests
- Commit: [fdd5ab2](commit.commit)
### Tested scenarios: 

[201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) **- Default syscheck configuration**
Redhat 8 - OK
Centos 7 - OK
Ubuntu 16.04 - OK
**Ubuntu 18.04 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Ubuntu 14.04 - OK
Amazon Linux 2 - OK
Windows 2019 - OK
**Windows 2016 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

- Windows 2012 - OK
[202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - **Real time monitoring**
Redhat 8 - OK
Centos 7 - OK
Ubuntu 16.04 - OK
**Ubuntu 18.04 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Ubuntu 14.04 - OK
Amazon Linux 2 - OK
Windows 2019 - OK
**Windows 2016 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Windows 2012 - OK
[203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - **Whodata**
Redhat 8 - OK
Centos 7 - OK
Ubuntu 16.04 - OK
**Ubuntu 18.04 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Ubuntu 14.04 - OK
Amazon Linux 2 - OK
Windows 2019 - OK
**Windows 2016 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Windows 2012 - OK
[204](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#204---whodata-linux---no-audit-installed-520) - **Whodata (no audit)**
Redhat 8 - OK
Centos 7 - OK
Ubuntu 16.04 - OK
**Ubuntu 18.04 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Ubuntu 14.04 - OK
Amazon Linux 2 - OK
Windows 2019 - OK
**Windows 2016 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Windows 2012 - OK
[205](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#205---use-of-restrict-option-linuxwindows-526) - **Restrict option**
Redhat 8 - OK
Centos 7 - OK
Ubuntu 16.04 - OK
**Ubuntu 18.04 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Ubuntu 14.04 - OK
Amazon Linux 2 - OK
Windows 2019 - OK
**Windows 2016 - NOT OK ([ossec.log](ossec.log) - [ossec.conf](ossec.conf))**

```json
    "errors":{
            "added":{
                "generated":5000,
                "received":4500               
    },
            "deleted":{
                "generated":5000,
                "received":4960 
    },
            "modified":{
                "generated":5000,
                "received":4960
    }
```

Windows 2012 - OK

**Comment by Zenidd** [comment]
## FIM System tests
- Commit: [fdd5ab2](commit.commit)
### Tested scenarios: 

- ### [201](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#201---default-syscheck-configuration-linuxwindows-480) **- Default syscheck configuration**

```json
"201":{
      "state":"SUCCESS"
}
```
- ###  [202](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#202---real-time-monitoring---add-linuxwindows-531) - **Real time monitoring**
```json
"202":{
      "state":"SUCCESS"
}
```
- ###  [203](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#203---whodata-linuxwindows-528) - **Whodata**
```json
"203":{
      "state":"FAILED",
      "data":{
         "agent0":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500

         "agent1":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500

         "agentN":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500
               
}
```
- ###  [204](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#204---whodata-linux---no-audit-installed-520) - **Whodata (no audit)**
```json
"204":{
      "state":"FAILED",
      "data":{
         "agent0":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500

         "agent1":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500

         "agentN":{
            "errors":{
               "added":{
                  "generated":5000,
                  "received":4500
               
}
```
- ###  [205](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list#205---use-of-restrict-option-linuxwindows-526) - **Restrict option**
```json
"205":{
      "state":"SUCCESS"
}
```

**Pull request closed without merging**
