### PR TITLE
IPv6 system tests: `agent-auth`

### PR DESCRIPTION
**Pull request by juliamagan**
|Related issue|
|---|
| #2266  |

_We can't merge this PR until #2304 is merged_

## Description

We have added a system test that checks if the agent enrollment works correctly for IPv4 and IPv6. This test uses `/var/ossec/bin/agent-auth`. Finally, it checks the manager and agent `ossec.log`, `client.keys`, and if the agent is `Active`. 

### Network configuration

| Manager |  Agent 	|  
|:--:|:--: |
| IPV4 	| IPV4|  	
| IPV6 	| IPV6 	| 
| Both	| Both 	| 
| Both	| IPV6 	|
| Both 	| IPV4 	| 
| IPV6| Both 	|
| IPV4| Both 	|

## Testing

With wazuh/wazuh `master` branch:

| Linux | Result | Notes |
|:--:|:--:|:--:|
|R1| 🔴 | We could not deploy the environment because the `ipv6` tag is invalid |

## Checks

- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] Python codebase is documented following the [QA-Docs Schema 2.0](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0).

### CODE REVIEW

**Comment by juliamagan** [comment]
## 15/12/2021


### Testing

We are testing in wazuh/wazuh `dev-support-ipv6-fix` development branch:

|Linux|Results|
|:--:|:--:|
|R1| [🔴 ](https://github.com/wazuh/wazuh-qa/files/7736833/R1-agent-auth.zip)| 

We got some timeout errors but we couldn't check them because the logs aren't stored. Also, we had to enable IPv6 in `remoted` manually.

## 17/12/2021


### Testing

Now, we can check the logs received in `ossec.log`. 

We are testing in wazuh/wazuh `dev-support-ipv6-fix` development branch:

|Linux|Results|
|:--:|:--:|
|R1| 🔵 |

**Comment by juliamagan** [comment]
## 20/12/2021

### Testing

We are testing in wazuh/wazuh `dev-support-ipv6-fix` development branch:

|Linux|Results|
|:--:|:--:|
|R1| [🔴 ](https://github.com/wazuh/wazuh-qa/files/7745140/R1-test-agent-auth.zip) |

**Comment by juliamagan** [comment]
## 21/12/2021

### Testing

We are testing in wazuh/wazuh `dev-support-ipv6-fix` development branch:


|Linux|Results|
|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7755386/R1-test-agent-auth.zip) |

**Comment by juliamagan** [comment]
## 28/12/2021

### Testing

We are testing in wazuh/wazuh `dev-support-ipv6` development branch:


|Linux|Results|
|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7783840/R1-test-agent-auth.zip) | 
|R2 | 🔵 |
|R3 |

**Comment by juliamagan** [comment]
## 31/01/2022

### Testing

We are testing in wazuh/wazuh `dev-support-ipv6` development branch:


|Linux|Results|
|:--:|:--:|
|R1|[🔴 ](https://github.com/wazuh/wazuh-qa/files/7973565/R1-test-agent-auth.zip) | 
|R2 | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7973567/R2-test-agent-auth.zip)|
|R3 | [🔴 ](https://github.com/wazuh/wazuh-qa/files/7973570/R3-test-agent-auth.zip)

**Comment by Rebits** [comment]
## 08/02/202
### Development Branch
`dev-support-ipv6`


## Testing

### `test_agent_authd`
|  OS  | Local       | Notes
|---    |---     |---    |
| R1   | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8025068/R3-2308-agent-auth.zip)  |  | 
| R2   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8025065/R1-2308-agent-auth.zip)  |    | 
| R3   | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/8025067/R2-2308-agent-auth.zip)  | |

* * * 
- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Pull request merged**
