### PR TITLE
Fix Upgrade_package_remove_vulnerability test 

### PR DESCRIPTION
**Pull request by MARCOSD4**
# Description

This PR aims to fix the `upgrade_package_remove_vulnerability` test from the vulnerability detector test cases since it was not working correctly because it assumed that the Grafana package was installed in version 9.2.0, but since it was not installed, no vulnerabilities were generated and the test did not pass. In this PR the Grafana download links have been changed and another package version required for CentOS systems has been added since it has been observed that Grafana packages for CentOS systems are different from the rest of the systems because a -1 is added at the end of the package. It has not been added as a precondition to install the 9.2.0 package as this will be done as part of the development of this PR https://github.com/wazuh/wazuh-qa/pull/5135.

### CODE REVIEW

**Comment by MARCOSD4** [comment]
## Testing performed

To test these changes, this build has been launched to build the instances https://ci.wazuh.info/job/Wazuh_QA_environment/1023/. Grafana version 9.2.0 has been previously installed in each one of the agents, following these steps https://grafana.com/grafana/download/9.2.0?edition=oss&platform=linux, to simulate that it would already be installed if we execute the complete test, since as I said before, this corresponds to another development. In addition, the yaml has been modified so that only the question test is executed. The results are as follows:

image

[Report.zip](https://github.com/wazuh/wazuh-qa/files/14722944/Report.zip)

**Comment by Rebits** [comment]
Duplicated. Changes applied in https://github.com/wazuh/wazuh-qa/issues/5103

**Review by juliamagan — CHANGES_REQUESTED** [review]
Why was Grafana 9.2.0 not being installed? Is there an issue that fixes this? Also, the changelog entry is missing.

**Comment by MARCOSD4** [comment]
The changes introduced here are the same ones that appear in the issue https://github.com/wazuh/wazuh-qa/issues/5103. Basically, they were made so that @rafabailon could include them in his development and that the tests would pass correctly in his test, as they did. Therefore, if Rafa's issue is merged, these changes should be included as well so I think this issue could be closed.

**Comment by juliamagan** [comment]
We are closing this PR since the changes have been introduced at https://github.com/wazuh/wazuh-qa/issues/5103.

**Pull request closed without merging**
