### PR TITLE
Fix Logcollector test for Windows and Solaris

### PR DESCRIPTION
**Pull request by MizugorouZ**
|Related issue|
|---|
| #2096|

## Description
Most of these tests were failing because after the merge of https://github.com/wazuh/wazuh-qa/pull/2043, the local internal options weren't set. Now the tests autoconfigure their local internal options.

## Package
| Version | Revision | Link|
|---|---|---|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.0-2096.logcollector.testing.msi|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/solaris/i386/11/wazuh-agent_v4.3.0-2096.logcollector.testing-sol11-i386.p5p|

### Windows Agent - tests/integration/test_logcollector

| OS | Jenkins | Notes |
|:--:|:--:|:--:|
| PS1 | [:red_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/16114/) | - |

### Solaris - tests/integration/test_logcollector

| OS | Jenkins | Notes |
|:--:|:--:|:--:|
| PS1 | [:red_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/16115/) | - |

* * * 

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

### CODE REVIEW

**Comment by Rebits** [comment]
## 16/11/21

After a few changes in `2096-logcollector-solaris-windows` most of the logcollector tests seems to work properly.  However test based on invalid configuration have to be skipped due to a possible issue in invalid configuration value validation for Windows agents, further research is required.

## Package
| Version | Revision | Link|
|---|---|---|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.0-2096.logcollector.testing.msi|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/solaris/i386/11/wazuh-agent_v4.3.0-2096.logcollector.testing-sol11-i386.p5p|


## Testing

### `test_logcollector`

|  Windows Server 2019  | Local   |Jenkins    | Notes
|---    |---    |---   |---  |
| PS1  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7548523/PS1_agent_windows_2222.zip) |  :large_blue_circle:   | 


|  Solaris 11  | Local   |Jenkins    | Notes
|---    |---    |---   |---  |
| PS1  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/7548537/PS1_agent_solaris.zip) |  :large_blue_circle:   | 
* * * 

- :green_circle: All pass
- :yellow_cirle:: Some warnings
- :red_circle:: Some errors/fails
- :large_blue_circle: In progress

**Comment by Rebits** [comment]
## 24/11/21
### Package
| Version | Revision | Link|
|---|---|---|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/windows/wazuh-agent-4.3.0-2096.logcollector.testing.msi|
4.3.0|2096.logcollector.testing|https://packages-dev.wazuh.com/warehouse/test/4.3/solaris/i386/11/wazuh-agent_v4.3.0-2096.logcollector.testing-sol11-i386.p5p|

## Testing

For the testing the fix of FileMonitor has been included, in order to avoid false positives produces by it. This should be removed when that change is incorporated into the master branch.

Due to the last changes in the branch, it is necessary to run again all the logcollector suite to ensure fixes does not affect to sanitized OS.

### Logcollector

Solaris seems to work correctly consistently

|  Solaris  | Local   | Jenkins    | Notes
|---    |---    |---   |---    |
 PS1   |  :large_blue_circle: |  [:large_blue_circle:  ](https://ci.wazuh.info/job/Test_integration/16485/console)  | 
| PS2   | :large_blue_circle:  |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16486/console)| |
 PS3   |  :large_blue_circle:   |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16487/console)  | |

*  *  *
Log collector for macOS worked almost perfectly before removing skipped tests, after the last changes `test_macos_log_process` fail when all the test suite is launched: https://ci.wazuh.info/job/Test_integration/16402/

|  macOS  | Local   | Jenkins     | Notes
|--   |---    |---   |--    |
 PS1   | :large_blue_circle:  |  [:large_blue_circle:  ](https://ci.wazuh.info/job/Test_integration/16485/console)  | 
| PS2   | :large_blue_circle:  |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16486/console)| |
 PS3   | :large_blue_circle:  |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16487/console)  | |

* * * 
Seems to work properly, but on rare occasions, it fails `test_custom_socket`. It is required further research before merging.

|  Centos7/8  | Local   | Jenkins     | Notes
|--   |---    |---   |--    |
 PS1   | :large_blue_circle:  |  [:large_blue_circle:  ](https://ci.wazuh.info/job/Test_integration/16485/console)  | 
| PS2   | :large_blue_circle:  |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16486/console)| |
 PS3   | :large_blue_circle:   |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16487/console)  | |

* * *
Windows presents multiple erratic errors. One of them, "System error 109 has occurred" has been investigated. This is caused for multiple reasons, especially hardware limitations. `Control_service` function has been modified in order to avoid this error. However, this should be investigated due to this is only produced in logcollector errors even in Jenkins.

|  Windows  | Local   | Jenkins     | Notes
|--   |---    |---   |--    |
 PS1   | :large_blue_circle: |  [:large_blue_circle:  ](https://ci.wazuh.info/job/Test_integration/16485/console)  | 
| PS2   | :large_blue_circle:  |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16486/console)| |
 PS3   | :large_blue_circle: |  [:large_blue_circle: ](https://ci.wazuh.info/job/Test_integration/16487/console)  | |

- :green_circle: All pass
- :yellow_circle: Some warnings
- :red_circle:  Some errrs/fails
- :large_blue_circle:  In progress

**Comment by juliamagan** [comment]
After skipping the following tests:
- `test_location_custom_sockets`
- `test_location_custom_sockets_offline`

**Comment by juliamagan** [comment]
I'll merge these changes to `2096-logcollector-manager-tests` branch and the logcollector module will be tested with that branch in every supported OS.

**Pull request merged**
