### PR TITLE
Fix inconsistent behavior on FileMonitor class

### LINKED ISSUE #1602: Refactor FileMonitor because of inconsistent behavior when heavy log activity
## Description
Some tests fail randomly because a certain message that the test expected to be written was not detected in the log file. 

After multiple tests, it appears that these errors originate in the `monitoring.py` module of the QA framework, specifically in the `FileMonitor` class, which is the one that finally checks if the related logs have been written. 

These logs are written to the log file correctly, but the `FileMonitor` class is not able to detect them when a large number of messages are written to the log file (**log flooding**). To verify this I have disabled the `sca` module, which generates a large number of logs and the tests involved have been running correctly.

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup local_internal_options.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

### Case:

|  Type | Description  |
|--|--|
|Test Path | test_vulnerability_detector/test_feeds/msu/test_missing_fields_msu_feed.py
| Error message |  "Could not find the message: 'Microsoft Security Update' feed finished successfully"

## Actual Behavior
Here you can see the instant when the test fails (test run using pytest **-sv** options):
```
test_vulnerability_detector/test_feeds/msu/test_missing_fields_msu_feed.py::test_invalid_msu_feed[MSU_configuration-missing: restart_required] 2021/07/14 08:22:34 wazuh-modulesd[60743] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/07/14 08:22:34 wazuh-modulesd[60743] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/07/14 08:22:34 wazuh-modulesd[60743] wmodules-osquery-monitor.c:78 at wm_osquery_monitor_read(): DEBUG: Logpath read: /var/log/osquery/osqueryd.results.log
2021/07/14 08:22:34 wazuh-modulesd[60743] wmodules-osquery-monitor.c:84 at wm_osquery_monitor_read(): DEBUG: configPath read: /etc/osquery/osquery.conf
2021/07/14 08:22:34 wazuh-modulesd[60743] wmodules-vuln-detector.c:609 at wm_vuldet_read_provider(): DEBUG: Added msu feed. Interval: 3600s | Multi path: '/home/vagrant/wazuh-qa/tests/integration/test_vulnerability_detector/test_feeds/msu/../../data/feeds/custom_msu.json$' | Multi url: 'none' | Update since: 0 | Timeout: 300s
2021-07-14 08:22:54,456 - wazuh_testing - ERROR - Could not find the message: 'Microsoft Security Update' feed finished successfully
2021-07-14 08:22:54,456 - wazuh_testing - ERROR - Results accumulated: 0
2021-07-14 08:22:54,456 - wazuh_testing - ERROR - Results expected: 1
FAILED2021-07-14T08:22:56.1626250976
```

The use case starts running at `08:22:34`:
`2021/07/14 08:22:34 wazuh-modulesd[60743] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec`

And ends at `08:22:54` due to timeout (20s):
`2021-07-14 08:22:54,456 - wazuh_testing - ERROR - Could not find the message: 'Microsoft Security Update' feed finished successfully`

However, by analyzing the `ossec.log` file, you can see that the message mentioned by the error has been written:
`2021/07/14 08:22:34 wazuh-modulesd:vulnerability-detector[60743] wm_vuln_detector.c:4077 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.`

As mentioned above, this behavior does not occur if modules that write a large number of messages to the log file, such as the `sca` module, are disabled.

## Expected Behavior
The test pass because FileMonitor detects the expected message.

## Note

| Environment Setup | Test Log   | Ossec Setting |
|--|--|--|
[Steps to create the testing environment](https://github.com/wazuh/wazuh-qa/files/6816104/environment_setup.txt) | [test_extra_fields_msu_feed_local.log](https://github.com/wazuh/wazuh-qa/files/6816052/test_extra_fields_msu_feed_local.log) |[ossec.conf.txt](https://github.com/wazuh/wazuh-qa/files/6816054/ossec.conf.txt)|

### Issues related to the problem described above:
- https://github.com/wazuh/wazuh-qa/issues/1542
- https://github.com/wazuh/wazuh-qa/issues/1547
- https://github.com/wazuh/wazuh-qa/issues/1548
- https://github.com/wazuh/wazuh-qa/issues/1553

### PR DESCRIPTION
**Pull request by MizugorouZ**
|Related issue|
|---|
|#1602  |

## Description
This PR close #1602. Following the issue #1602, a problem in the `FileMonitor` class made some tests fail randomly. At first, it was thought that the issue was that `FileMonitor` skipped messages in case of logs flood, resulting in false positives cases. However, after some research, we found that `FileMonitor` wasn't skipping messages, and the problem was that when there is a large number of messages in the log file, it takes a lot of time so we get a timeout error.

There are 2 ways of passing the tests: disabling the modules that generate lots of logs or specifying a big timeout. The first one is quicker because there are fewer messages. The second option passes the tests with an average time of 5-6 minutes ([example](https://github.com/wazuh/wazuh-qa/files/7006888/r1_filemonitor_timeout.zip)).

After some more research, we discovered that the problem is in the `start` method of `FileMonitor`. In this method, the `QueueMonitor` object is created. This object uses  `FileTailer`  for collecting messages from a file and uses defined callbacks for filtering them.

`FileMonitor` allows 2 methods for searching the messages. One of them deletes the messages from the `QueueMonitor`, while the other one copies the queue and uses `peek` method. Using `peek` method is computationally expensive because it copies all the queue for each received message.

Finally, we saw that in the start method of the `FileMonitor` class, the file_tailer is copied depending on the `update_position` value. We thought that for all tests that use `FileMonitor`, it might be possible to use `update_position=True` when creating the `QueueMonitor`. With this change, we force `QueueMonitor` to update the position, which will make it work faster.

### Packages details

|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Local internal options
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Test path
`test_vulnerability_detector/test_feeds/msu/test_missing_fields_msu_feed.py`

## Tests results

| **Linux manager**  |  **Status** | **Results** |
|:--:|:--: |:--: |
|**R1**| :green_circle: | [Test results](https://github.com/wazuh/wazuh-qa/files/6999693/r1_filemonitor_update_position.zip) | 
|**R2**| :green_circle: | [Test results](https://github.com/wazuh/wazuh-qa/files/6999694/r2_filemonitor_update_position.zip) |
|**R3**| :green_circle: | [Test results](https://github.com/wazuh/wazuh-qa/files/6999695/r3_filemonitor_update_position.zip) |

### CODE REVIEW

**Comment by Rebits** [comment]
This fix sees to solves the problem. Further testing is required due to this affects almost every test in the repository.


| **Linux manager**  |  **Status** |
|:--:|:--: |
|**R1**|  [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7008145/r1_file_monitor.zip)
|**R2**| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7008146/r2_file_monitor.zip)
|**R3**| [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7008147/r3_file_monitor.zip)

**Comment by MizugorouZ** [comment]
The branch `1774-4.2-full-green-local` contains all the changes in test from `1516-4.2.0-full-green`. I applied the FileMonitor fix of this PR to the branch `1774-4.2-full-green-local` and executed all integration test (except FIM):
| Wazuh QA: Branch | Status | Test results |
|:--:|:--:|:--:|
| 1774-4.2-full-green-local | :green_circle: (:yellow_circle: in test_api) | [Results](https://github.com/wazuh/wazuh-qa/files/7128592/FileMonitor_Fix_Tests.zip) |

**Review by juliamagan — APPROVED** [review]

**Comment by juliamagan** [comment]
## Tests results

| **Linux manager**  |  **Status** |
|:--:|:--: |
|**R1**| 
|**R2**| 
|**R3**|

**Comment by Deblintrake09** [comment]
<p>Tests result in branch <code>1602-4.2.0-fix-file-monitor</code> in Local VMs</p>


Test | Manager/Agent | OS | Date | Status | Note
-- | -- | -- | -- | -- | --
| `test_vulnerability_detector` | Manager | CentOS | 2021/11/02 | [:red_circle:](https://github.com/wazuh/wazuh-qa/files/7470111/ResultsVulnerabilityDetector.zip) | - | 
| `test_fim` | Linux Agent | CentOS | 2021/11/02 | [:red_circle:](https://github.com/wazuh/wazuh-qa/files/7470107/Fim-LinuxAgent.zip) | - |

**Comment by Deblintrake09** [comment]
This PR doesn't seem to fix issues in Vulnerability Detector, so I've blocked again all tests that were unblocked by this PR to run VD and try to get a full green. The I will proceed to debug and fix the tests if possible.

### Jenkins Executions
Test | Manager/Agent | OS | Date | Status | Note
|-- | -- | -- | -- | -- | --|
| `test_vulnerability_detector/test_windows` | Manager | CentOS | 2021/11/04 | [:large__blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15001/) | - | 
| `test_vulnerability_detector/test_scan_results` | Manager | CentOS | 2021/11/04 | [:large__blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15000/) | - | 
| `test_vulnerability_detector/test_providers` | Manager | CentOS | 2021/11/04 | [:large__blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14999/) | - | 
| `test_vulnerability_detector/test_general_settings` | Manager | CentOS | 2021/11/04 | [:large__blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15004/) | - | 
| `test_vulnerability_detector/test_feeds` | Manager | CentOS | 2021/11/04 | [:large__blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14997/) | - |

**Comment by Deblintrake09** [comment]
## Update 2021/11/09

WPK Tests ran with package 4.2.4 on 1602-4.2-fix-file-monitor
### Test Executions
Test | Manager/Agent | OS | Date | Status | Note
|-- | -- | -- | -- | -- | --|
| `test_wpk/` | Manager -Local | CentOS | 2021/11/09 | [ :green_circle: ](https://github.com/wazuh/wazuh-qa/files/7505398/ResultsWPK-Manager.zip) | - | 
| `test_wpk/` | Agent - Local | Windows | 2021/11/09 | [ :green_circle: ](https://github.com/wazuh/wazuh-qa/files/7505414/ResultsWPK.-.4.2.4.in.4.2.4.repo.zip) | - | 
| `test_wpk/` | Agent - Local | Linux | 2021/11/08 | [ :green_circle: ](https://github.com/wazuh/wazuh-qa/files/7505397/ResultsWPK-Linux-Agent.zip) | - |

**Comment by MizugorouZ** [comment]
Tests result in branch `1602-4.2.0-fix-file-monitor` in Jenkins after bringing all changes from `4.2` :

| Test | Manager/Agent | OS | Date | Status | Note |
|:--:|:--:|:--:|:--:|:--:|:--:|
| `test_active_response` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14439/) | - |
| `test_active_response` | Agent | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14471/) | - |
| `test_active_response` | Agent | Windows | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14472/) | - |
| `test_agentd` | Agent | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14476/) | - |
| `test_agentd` | Agent | Windows | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14474/) | - |
| `test_analysisd` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14440/) | - |
| `test_api` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14441/) | - |
| `test_authd` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14453/) | - |
| `test_enrollment` | Agent | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14632/) | - |
| `test_enrollment` | Agent | Windows | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14633/) | - |
| `test_fim` | Manager | CentOS | 2021/11/03 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15018/) | `test_fim/test_files/test_nodiff/` and `test_fim/test_files/test_skip/test_skip_nfs.py` skipped |
| `test_fim` | Agent | CentOS | 2021/11/03 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15019/) | `test_fim/test_files/test_nodiff/` and `test_fim/test_files/test_skip/test_skip_nfs.py` skipped |
| `test_fim` | Agent | Windows | 2021/11/03 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15028/) | `test_fim/test_files/test_nodiff/` and `test_fim/test_files/test_skip/test_skip_nfs.py` skipped |
| `test_fim` | Agent | Solaris | 2021/11/03 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7487305/01-fimSolaris-1721.zip) | `test_fim/test_files/test_nodiff/` and `test_fim/test_files/test_skip/test_skip_nfs.py` skipped |
| `test_fim` | Agent | MacOS | 2021/11/03 | [:green_circle:](https://github.com/wazuh/wazuh-qa/files/7487461/01-fimMacOS-1721.zip) | `test_fim/test_files/test_nodiff/` and `test_fim/test_files/test_skip/test_skip_nfs.py` skipped |
| `test_gcloud` | Manager | CentOS | 2021/10/28 | [:red_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14454/) | Fails due to known issue #1906 |
| `test_logtest` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14455/) | - |
| `test_remoted` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14459/) | - |
| `test_rids` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14460/) | - |
| `test_rootcheck` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14461/) | - |
| `test_vulnerability_detector` | Manager | CentOS | 2021/10/28 | [:red_circle:]() | - |
| `test_wazuh_db` | Manager | CentOS | 2021/10/28 | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/14462/) | - |
| `test_wpk` | Manager | CentOS | 2021/11/09 | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15554/) | - |
| `test_wpk` | Agent | CentOS | 2021/11/09 | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15555/) | - |
| `test_wpk` | Agent | Windows | 2021/11/09 | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/15556/) | - |

**Comment by snaow** [comment]
LGTM.

Many FIM tests are re-enabled in this PR since the main issue with them was this FileMonitor bug. 
Vulnerability detector tests affected by the FileMonitor bug are not anymore, but they are still blocked due to a different issue.

**Pull request merged**
