### PR TITLE
Change system tests docker image

### PR DESCRIPTION
**Pull request by Rebits**
|Related issue|
|-------------|
|        #4592      |

## Description

This PR changes the docker image of System tests in order to fix gcc compilation error

### Updated

- Changed System Tests Docker image

---

## Testing performed

| Tester             | Environment | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @Rebits (Developer)  |   One Manager One Agent        | :no_entry_sign:  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/pull/4655#issuecomment-1785158154) |         |         | Nothing to highlight |

### CODE REVIEW

**Comment by Rebits** [comment]
Only one manager agent environment test has been conducted. It is unnecessary to perform exhaustive testing for the remaining tests, as the changes are identical for all test environments

[OneManagerAgent.zip](https://github.com/wazuh/wazuh-qa/files/13205408/OneManagerAgent.zip): :green_circle:

**Comment by pro-akim** [comment]
## Review Notes
Reviewing different environments:

|Environment|Result|
|---|---|
|agentless_cluster|:black_circle:|
|basic_cluster|:black_circle:|
|basic_environment|:black_circle:|
|big_cluster_40_agents|:black_circle:|
|enrollment_cluster|:black_circle:|
|four_manager_disconnected_node|:black_circle:|
|manager_agent|:black_circle:|
|one_manager_agent|:black_circle:|

|Status|Description|
|---|---|
|:black_circle:|Available|
|:yellow_circle:|In progress|
|:green_circle:|Passed|
|:red_circle:|Failed|

**Comment by pro-akim** [comment]
## Review Notes:

Trying to run the test in EC2 and the following error message is present


<details>
```
TASK [roles/manager-role : Install manager] ***********************************************************************************************************************************************************************
fatal: [wazuh-manager]: FAILED! => changed=true 
  cmd: ./install.sh
  delta: '0:01:26.042095'
  end: '2023-10-31 10:54:18.944105'
  msg: non-zero return code
  rc: 1
  start: '2023-10-31 10:52:52.902010'
  stderr: |-
    Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
    Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
    Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
    Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
  
    gzip: nlohmann.tar.gz: not in gzip format
    Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
    Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
    Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
    Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
    Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
    Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
    Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
    Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
        [34;1mCC[0m [37;1mlibwazuhext.so[0m
    In file included from /wazuh/src/data_provider/src/sysInfoLinux.cpp:15:
    /wazuh/src/data_provider/src/packages/modernPackageDataRetriever.hpp: In static member function 'static void ModernFactoryPackagesCreator<true>::getPackages(const std::map<std::__cxx11::basic_string<char>, std::set<std::__cxx11::basic_string<char> > >&, std::function<void(nlohmann::json_abi_v3_11_2::basic_json<>&)>)':
    /wazuh/src/data_provider/src/packages/modernPackageDataRetriever.hpp:53:18: error: cannot deduce template arguments for 'PYPI' from ()
                 PYPI().getPackages(paths.at("PYPI"), callback);
                      ^
    /wazuh/src/data_provider/src/packages/modernPackageDataRetriever.hpp:54:17: error: cannot deduce template arguments for 'NPM' from ()
                 NPM().getPackages(paths.at("NPM"), callback);
                     ^
    make[4]: *** [CMakeFiles/sysinfo.dir/build.make:167: CMakeFiles/sysinfo.dir/src/sysInfoLinux.cpp.o] Error 1
    make[3]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sysinfo.dir/all] Error 2
    make[2]: *** [Makefile:95: all] Error 2
    make[1]: *** [Makefile:1673: build_sysinfo] Error 2
    make[1]: *** Waiting for unfinished jobs....
    make: *** [Makefile:791: server] Error 2
  stderr_lines: <omitted>
  stdout: |2-
  
     Wazuh v4.7.0 (Rev. 40701) Installation Script - https://www.wazuh.com
  
     You are about to start the installation process of Wazuh.
     You must have a C compiler pre-installed in your system.
  
      - System: Linux wazuh-manager 6.2.0-1012-aws (debian 10.0)
      - User: root
      - Host: wazuh-manager
  
  
      -- Press ENTER to continue or Ctrl-C to abort. --
  
        - Installation will be made at  /var/ossec .
  
    3- Configuring Wazuh.
  
      3.1- Do you want e-mail notification? (y/n) [n]:
       --- Email notification disabled.
  
      3.2- Do you want to run the integrity check daemon? (y/n) [y]:
       - Not running syscheck (integrity check daemon).
  
      3.3- Do you want to run the rootkit detection engine? (y/n) [y]:
       - Not running rootcheck (rootkit detection).
  
      3.5- Active response allows you to execute a specific
           command based on the events received.
           By default, no active responses are defined.
  
       - Default white list for the active response:
          - 127.0.0.11
          - 2001:4860:4860::8888
          - 2001:4860:4860::8844
  
       - Do you want to add more IPs to the white list? (y/n)? [n]:
      3.6- Do you want to enable remote syslog (port 514 udp)? (y/n) [y]:
       - Remote syslog enabled.
  
      3.7 - Do you want to run the Auth daemon? (y/n) [y]:
       - Running Auth daemon.
  
      3.8- Do you want to start Wazuh after the installation? (y/n) [y]:
       - Wazuh will start at the end of installation.
  
      3.9- Setting the configuration to analyze the following logs:
  
        -- /var/ossec/logs/active-responses.log
        -- /var/log/dpkg.log
  
     - If you want to monitor any other file, just change
       the ossec.conf and add a new localfile entry.
       Any questions about the configuration can be answered
       by visiting us online at https://documentation.wazuh.com/.
  
  
       --- Press ENTER to continue ---
  
    4- Installing the system
  
    DIR="/var/ossec"
     - Running the Makefile
  
    curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/cJSON.tar.gz || true
    cd external && test -e cJSON.tar.gz && gunzip cJSON.tar.gz || true
    cd external && test -e cJSON.tar && tar -xf cJSON.tar || true
    test -e external/cJSON.tar && rm external/cJSON.tar || true
    test -d external/cJSON ||\
    (curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/cJSON.tar.gz &&\
    cd external && gunzip cJSON.tar.gz && tar -xf cJSON.tar && rm cJSON.tar)
    curl -so external/curl.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/curl.tar.gz || true
    cd external && test -e curl.tar.gz && gunzip curl.tar.gz || true
    cd external && test -e curl.tar && tar -xf curl.tar || true
    test -e external/curl.tar && rm external/curl.tar || true
    test -d external/curl ||\
    (curl -so external/curl.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/curl.tar.gz &&\
    cd external && gunzip curl.tar.gz && tar -xf curl.tar && rm curl.tar)
    curl -so external/libdb.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libdb.tar.gz || true
    cd external && test -e libdb.tar.gz && gunzip libdb.tar.gz || true
    cd external && test -e libdb.tar && tar -xf libdb.tar || true
    test -e external/libdb.tar && rm external/libdb.tar || true
    test -d external/libdb ||\
    (curl -so external/libdb.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libdb.tar.gz &&\
    cd external && gunzip libdb.tar.gz && tar -xf libdb.tar && rm libdb.tar)
    curl -so external/libffi.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libffi.tar.gz || true
    cd external && test -e libffi.tar.gz && gunzip libffi.tar.gz || true
    cd external && test -e libffi.tar && tar -xf libffi.tar || true
    test -e external/libffi.tar && rm external/libffi.tar || true
    test -d external/libffi ||\
    (curl -so external/libffi.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libffi.tar.gz &&\
    cd external && gunzip libffi.tar.gz && tar -xf libffi.tar && rm libffi.tar)
    curl -so external/libyaml.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libyaml.tar.gz || true
    cd external && test -e libyaml.tar.gz && gunzip libyaml.tar.gz || true
    cd external && test -e libyaml.tar && tar -xf libyaml.tar || true
    test -e external/libyaml.tar && rm external/libyaml.tar || true
    test -d external/libyaml ||\
    (curl -so external/libyaml.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libyaml.tar.gz &&\
    cd external && gunzip libyaml.tar.gz && tar -xf libyaml.tar && rm libyaml.tar)
    curl -so external/openssl.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/openssl.tar.gz || true
    cd external && test -e openssl.tar.gz && gunzip openssl.tar.gz || true
    cd external && test -e openssl.tar && tar -xf openssl.tar || true
    test -e external/openssl.tar && rm external/openssl.tar || true
    test -d external/openssl ||\
    (curl -so external/openssl.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/openssl.tar.gz &&\
    cd external && gunzip openssl.tar.gz && tar -xf openssl.tar && rm openssl.tar)
    curl -so external/procps.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/procps.tar.gz || true
    cd external && test -e procps.tar.gz && gunzip procps.tar.gz || true
    cd external && test -e procps.tar && tar -xf procps.tar || true
    test -e external/procps.tar && rm external/procps.tar || true
    test -d external/procps ||\
    (curl -so external/procps.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/procps.tar.gz &&\
    cd external && gunzip procps.tar.gz && tar -xf procps.tar && rm procps.tar)
    curl -so external/sqlite.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/sqlite.tar.gz || true
    cd external && test -e sqlite.tar.gz && gunzip sqlite.tar.gz || true
    cd external && test -e sqlite.tar && tar -xf sqlite.tar || true
    test -e external/sqlite.tar && rm external/sqlite.tar || true
    test -d external/sqlite ||\
    (curl -so external/sqlite.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/sqlite.tar.gz &&\
    cd external && gunzip sqlite.tar.gz && tar -xf sqlite.tar && rm sqlite.tar)
    curl -so external/zlib.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/zlib.tar.gz || true
    cd external && test -e zlib.tar.gz && gunzip zlib.tar.gz || true
    cd external && test -e zlib.tar && tar -xf zlib.tar || true
    test -e external/zlib.tar && rm external/zlib.tar || true
    test -d external/zlib ||\
    (curl -so external/zlib.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/zlib.tar.gz &&\
    cd external && gunzip zlib.tar.gz && tar -xf zlib.tar && rm zlib.tar)
    curl -so external/audit-userspace.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/audit-userspace.tar.gz || true
    cd external && test -e audit-userspace.tar.gz && gunzip audit-userspace.tar.gz || true
    cd external && test -e audit-userspace.tar && tar -xf audit-userspace.tar || true
    test -e external/audit-userspace.tar && rm external/audit-userspace.tar || true
    test -d external/audit-userspace ||\
    (curl -so external/audit-userspace.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/audit-userspace.tar.gz &&\
    cd external && gunzip audit-userspace.tar.gz && tar -xf audit-userspace.tar && rm audit-userspace.tar)
    curl -so external/msgpack.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/msgpack.tar.gz || true
    cd external && test -e msgpack.tar.gz && gunzip msgpack.tar.gz || true
    cd external && test -e msgpack.tar && tar -xf msgpack.tar || true
    test -e external/msgpack.tar && rm external/msgpack.tar || true
    test -d external/msgpack ||\
    (curl -so external/msgpack.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/msgpack.tar.gz &&\
    cd external && gunzip msgpack.tar.gz && tar -xf msgpack.tar && rm msgpack.tar)
    curl -so external/bzip2.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/bzip2.tar.gz || true
    cd external && test -e bzip2.tar.gz && gunzip bzip2.tar.gz || true
    cd external && test -e bzip2.tar && tar -xf bzip2.tar || true
    test -e external/bzip2.tar && rm external/bzip2.tar || true
    test -d external/bzip2 ||\
    (curl -so external/bzip2.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/bzip2.tar.gz &&\
    cd external && gunzip bzip2.tar.gz && tar -xf bzip2.tar && rm bzip2.tar)
    curl -so external/nlohmann.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/nlohmann.tar.gz || true
    cd external && test -e nlohmann.tar.gz && gunzip nlohmann.tar.gz || true
    cd external && test -e nlohmann.tar && tar -xf nlohmann.tar || true
    test -e external/nlohmann.tar && rm external/nlohmann.tar || true
    test -d external/nlohmann ||\
    (curl -so external/nlohmann.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/nlohmann.tar.gz &&\
    cd external && gunzip nlohmann.tar.gz && tar -xf nlohmann.tar && rm nlohmann.tar)
    curl -so external/googletest.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/googletest.tar.gz || true
    cd external && test -e googletest.tar.gz && gunzip googletest.tar.gz || true
    cd external && test -e googletest.tar && tar -xf googletest.tar || true
    test -e external/googletest.tar && rm external/googletest.tar || true
    test -d external/googletest ||\
    (curl -so external/googletest.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/googletest.tar.gz &&\
    cd external && gunzip googletest.tar.gz && tar -xf googletest.tar && rm googletest.tar)
    curl -so external/libpcre2.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libpcre2.tar.gz || true
    cd external && test -e libpcre2.tar.gz && gunzip libpcre2.tar.gz || true
    cd external && test -e libpcre2.tar && tar -xf libpcre2.tar || true
    test -e external/libpcre2.tar && rm external/libpcre2.tar || true
    test -d external/libpcre2 ||\
    (curl -so external/libpcre2.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libpcre2.tar.gz &&\
    cd external && gunzip libpcre2.tar.gz && tar -xf libpcre2.tar && rm libpcre2.tar)
    curl -so external/libplist.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libplist.tar.gz || true
    cd external && test -e libplist.tar.gz && gunzip libplist.tar.gz || true
    cd external && test -e libplist.tar && tar -xf libplist.tar || true
    test -e external/libplist.tar && rm external/libplist.tar || true
    test -d external/libplist ||\
    (curl -so external/libplist.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libplist.tar.gz &&\
    cd external && gunzip libplist.tar.gz && tar -xf libplist.tar && rm libplist.tar)
    curl -so external/pacman.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/pacman.tar.gz || true
    cd external && test -e pacman.tar.gz && gunzip pacman.tar.gz || true
    cd external && test -e pacman.tar && tar -xf pacman.tar || true
    test -e external/pacman.tar && rm external/pacman.tar || true
    test -d external/pacman ||\
    (curl -so external/pacman.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/pacman.tar.gz &&\
    cd external && gunzip pacman.tar.gz && tar -xf pacman.tar && rm pacman.tar)
    curl -so external/libarchive.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/libarchive.tar.gz || true
    cd external && test -e libarchive.tar.gz && gunzip libarchive.tar.gz || true
    cd external && test -e libarchive.tar && tar -xf libarchive.tar || true
    test -e external/libarchive.tar && rm external/libarchive.tar || true
    test -d external/libarchive ||\
    (curl -so external/libarchive.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/libarchive.tar.gz &&\
    cd external && gunzip libarchive.tar.gz && tar -xf libarchive.tar && rm libarchive.tar)
    curl -so external/popt.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/popt.tar.gz || true
    cd external && test -e popt.tar.gz && gunzip popt.tar.gz || true
    cd external && test -e popt.tar && tar -xf popt.tar || true
    test -e external/popt.tar && rm external/popt.tar || true
    test -d external/popt ||\
    (curl -so external/popt.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/popt.tar.gz &&\
    cd external && gunzip popt.tar.gz && tar -xf popt.tar && rm popt.tar)
    curl -so external/rpm.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/rpm.tar.gz || true
    cd external && test -e rpm.tar.gz && gunzip rpm.tar.gz || true
    cd external && test -e rpm.tar && tar -xf rpm.tar || true
    test -e external/rpm.tar && rm external/rpm.tar || true
    test -d external/rpm ||\
    (curl -so external/rpm.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/rpm.tar.gz &&\
    cd external && gunzip rpm.tar.gz && tar -xf rpm.tar && rm rpm.tar)
    curl -so external/cpython.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/cpython.tar.gz || true
    cd external && test -e cpython.tar.gz && gunzip cpython.tar.gz || true
    test -e external/cpython.tar ||\
    (curl -so external/cpython.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/cpython.tar.gz &&\
    cd external && gunzip cpython.tar.gz && tar -xf cpython.tar && rm cpython.tar)
    test -d external/cpython || (cd external && gzip cpython.tar)
    curl -so external/jemalloc.tar.gz https://packages.wazuh.com/deps/22/libraries/linux/amd64/jemalloc.tar.gz || true
    cd external && test -e jemalloc.tar.gz && gunzip jemalloc.tar.gz || true
    cd external && test -e jemalloc.tar && tar -xf jemalloc.tar || true
    test -e external/jemalloc.tar && rm external/jemalloc.tar || true
    test -d external/jemalloc ||\
    (curl -so external/jemalloc.tar.gz https://packages.wazuh.com/deps/22/libraries/sources/jemalloc.tar.gz &&\
    cd external && gunzip jemalloc.tar.gz && tar -xf jemalloc.tar && rm jemalloc.tar)
    cp /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6
    cp /usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so.1 libgcc_s.so.1
    strip -x libgcc_s.so.1
    strip -x libstdc++.so.6
    make build_sysinfo build_shared_modules build_syscollector
    make[1]: Entering directory '/wazuh/src'
    cd data_provider/ && mkdir -p build && cd build && cmake     .. && make
    cd shared_modules/dbsync/ && mkdir -p build && cd build && cmake    .. && make
    -- The C compiler identification is GNU 8.3.0
    -- The C compiler identification is GNU 8.3.0
    -- The CXX compiler identification is GNU 8.3.0
    -- The CXX compiler identification is GNU 8.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test HAS_OPTIONAL
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /wazuh/src/shared_modules/dbsync/build
    make[2]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    make[3]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    Scanning dependencies of target dbsync
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    [ 10%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync.cpp.o
    -- Performing Test HAS_OPTIONAL - Success
    -- Performing Test HAS_FILESYSTEM
    -- Performing Test HAS_FILESYSTEM - Success
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /wazuh/src/data_provider/build
    make[2]: Entering directory '/wazuh/src/data_provider/build'
    make[3]: Entering directory '/wazuh/src/data_provider/build'
    make[4]: Entering directory '/wazuh/src/data_provider/build'
    Scanning dependencies of target sysinfo
    make[4]: Leaving directory '/wazuh/src/data_provider/build'
    make[4]: Entering directory '/wazuh/src/data_provider/build'
    [  7%] Building CXX object CMakeFiles/sysinfo.dir/src/network/networkInterfaceLinux.cpp.o
    [ 14%] Building CXX object CMakeFiles/sysinfo.dir/src/osinfo/sysOsParsers.cpp.o
    [ 20%] Building CXX object CMakeFiles/dbsync.dir/src/dbsyncPipelineFactory.cpp.o
    [ 30%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync_implementation.cpp.o
    [ 21%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/packageLinuxParserApk.cpp.o
    [ 40%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_dbengine.cpp.o
    [ 28%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/packageLinuxParserDeb.cpp.o
    [ 35%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/packageLinuxParserExtra.cpp.o
    [ 50%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_wrapper.cpp.o
    [ 60%] Linking CXX shared library lib/libdbsync.so
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    [ 60%] Built target dbsync
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    Scanning dependencies of target dbsync_example
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    [ 70%] Building CXX object example/CMakeFiles/dbsync_example.dir/main.cpp.o
    [ 80%] Linking CXX executable ../bin/dbsync_example
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    [ 80%] Built target dbsync_example
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    [ 42%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/packageLinuxParserRpm.cpp.o
    Scanning dependencies of target dbsync_test_tool
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/dbsync/build'
    [ 90%] Building CXX object testtool/CMakeFiles/dbsync_test_tool.dir/main.cpp.o
    [ 50%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/packageLinuxParserRpmLegacy.cpp.o
    [ 57%] Building CXX object CMakeFiles/sysinfo.dir/src/packages/rpmPackageManager.cpp.o
    [ 64%] Building CXX object CMakeFiles/sysinfo.dir/src/sysInfoLinux.cpp.o
    [100%] Linking CXX executable ../bin/dbsync_test_tool
    make[4]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    [100%] Built target dbsync_test_tool
    make[3]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    make[2]: Leaving directory '/wazuh/src/shared_modules/dbsync/build'
    cd shared_modules/rsync/ && mkdir -p build && cd build && cmake     .. && make
    -- The C compiler identification is GNU 8.3.0
    -- The CXX compiler identification is GNU 8.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    make[4]: Leaving directory '/wazuh/src/data_provider/build'
    make[3]: Leaving directory '/wazuh/src/data_provider/build'
    make[2]: Leaving directory '/wazuh/src/data_provider/build'
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /wazuh/src/shared_modules/rsync/build
    make[2]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    make[3]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    Scanning dependencies of target rsync
    make[4]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    [ 12%] Building CXX object CMakeFiles/rsync.dir/src/rsync.cpp.o
    [ 25%] Building CXX object CMakeFiles/rsync.dir/src/rsyncImplementation.cpp.o
    [ 37%] Linking CXX shared library lib/librsync.so
    make[4]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    [ 37%] Built target rsync
    make[4]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    Scanning dependencies of target rsync_test_tool
    make[4]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    make[4]: Entering directory '/wazuh/src/shared_modules/rsync/build'
    [ 50%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/main.cpp.o
    [ 62%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/agentEmulator.cpp.o
    [ 75%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/oneTimeSync.cpp.o
    [ 87%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/managerEmulator.cpp.o
    [100%] Linking CXX executable ../bin/rsync_test_tool
    make[4]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    [100%] Built target rsync_test_tool
    make[3]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    make[2]: Leaving directory '/wazuh/src/shared_modules/rsync/build'
    make[1]: Leaving directory '/wazuh/src'
  
     Error 0x5.
     Building error. Unable to finish the installation.
  stdout_lines: <omitted>
```
</details>

**Comment by Rebits** [comment]
### Big 40 agents cluster failure

Deployment fails due to the lack of space to perform the provision. 
This could be related to the increasal size of the virtual size of the new image
```
80f92af5104e   wazuh/ubuntu_jammy_system_tests:1     "/panic/entry tail -…"   21 minutes ago   Up 21 minutes                                                                                 wazuh-agent1        31MB (virtual 9.19GB)
```

However it is important to notice that this Virtual size is used only once irregardless of how many containers are started from the same image. So, this should not lead into a unstable environment if we increase the resources of the host.
In addition it is proposed to delete the` /wazuh` content in all the agents, in order to decrease the required resources of the environment

### Manager agent

Fixed in https://github.com/wazuh/wazuh-qa/pull/4655/commits/5d9e29732ef70bfa70aea65c785b7b882510e115

**Comment by pro-akim** [comment]
## Update

Manager agent :green_circle: 
[manager_agent.zip](https://github.com/wazuh/wazuh-qa/files/13224842/manager_agent.zip)

**Comment by pro-akim** [comment]
## Review Notes Upgrade
Tested enrollment with 4.6.0

Still, same errors were detected

[enrollment 4.6.0.zip](https://github.com/wazuh/wazuh-qa/files/13236512/enrollment.4.6.0.zip)

**Comment by Rebits** [comment]
Not related with the change.
The error output is the following :
```
 ------------------------------Captured stderr call------------------------------ 
2023-11-02 09:44:47,390 - wazuh_testing - DEBUG - Add new file composer process for wazuh-master and path: var/ossec/logs/cluster.log
2023-11-02 09:44:47,392 - wazuh_testing - DEBUG - Starting file composer for wazuh-master and path: var/ossec/logs/cluster.log. Composite file in /home/akim/Desktop/wazuh-qa/tests/system/test_cluster/test_agent_groups/tmp/wazuh-master_cluster.log.tmp
2023-11-02 09:44:47,392 - wazuh_testing - DEBUG - Add new file monitor process for wazuh-master and path: var/ossec/logs/cluster.log
2023-11-02 09:44:47,395 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-master and message: .*Agent-groups send full.* Finished.*
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wazuh_testing/tools/monitoring.py", line 960, in file_composer
    content = self.host_manager.get_file_content(host, path).split('\n')
  File "/usr/local/lib/python3.10/dist-packages/wazuh_testing/tools/system.py", line 139, in get_file_content
    return self.get_host(host).file(file_path).content_string
  File "/home/akim/.local/lib/python3.10/site-packages/testinfra/modules/file.py", line 153, in content_string
    return self._get_content(True)
  File "/home/akim/.local/lib/python3.10/site-packages/testinfra/modules/file.py", line 132, in _get_content
    raise RuntimeError("Unexpected output %s" % (out,))
RuntimeError: Unexpected output CommandResult(command=b'cat -- var/ossec/logs/cluster.log', exit_status=1, stdout=None, stderr=b'cat: var/ossec/logs/cluster.log: No such file or directory\n')
```

We can see that the test is failing due to a bad file path `var/ossec/logs/cluster.log`, instead of `/var/ossec/logs/cluster.log`

**Comment by pro-akim** [comment]
## Review Notes 
Reviewing different environments:       
      
|Environment|Result|Report|Note|
|---|---|---|---|
|agentless_cluster|:green_circle:| [agentless_cluster.zip](https://github.com/wazuh/wazuh-qa/files/13206664/agentless_cluster.zip)
|basic_cluster|:green_circle:| [basic_cluster.zip](https://github.com/wazuh/wazuh-qa/files/13215205/basic_cluster.zip)
|basic_environment|:green_circle:|[basic_environment.zip](https://github.com/wazuh/wazuh-qa/files/13216210/basic_environment.zip)
|big_cluster_40_agents|:green_circle:| [big_40.zip](https://github.com/wazuh/wazuh-qa/files/13221282/big_40.zip) |Size of new containers take too much space to create an infrastructure of 40 agents, but running it with packages works
|enrollment_cluster|:green_circle:|[enrollment_cluster.zip](https://github.com/wazuh/wazuh-qa/files/13226436/enrollment_cluster.zip) | fixes done [enrollment_cluster_fixed.zip](https://github.com/wazuh/wazuh-qa/files/13238723/enrollment_cluster_fixed.zip)
agerAgent.zip)
|four_manager_disconnected_node|:green_circle:| [four_manager.zip](https://github.com/wazuh/wazuh-qa/files/13219768/four_manager.zip)
|manager_agent|:green_circle:|https://github.com/wazuh/wazuh-qa/files/13224842/manager_agent.zip | 
|one_manager_agent|:green_circle:| [one_manager_agent.zip](https://github.com/wazuh/wazuh-qa/files/13205408/OneMan





|Status|Description|
|---|---|
|:black_circle:|Available|
|:yellow_circle:|In progress|
|:green_circle:|Passed|
|:red_circle:|Failed|
|:white_circle:|Skipped|

**Review by pro-akim — APPROVED** [review]
## Review Notes
LGTM

**Review by damarisg — APPROVED** [review]

**Review by davidjiglesias — APPROVED** [review]

**Pull request merged**
