### PR TITLE
Remoted IT - Fix imports, fixtures and warnings

### LINKED ISSUE #2562: Remoted IT - Fix imports in `remote.py`
## Description

After the merge of #1496, remoted tests started failing on nightly runs. The imports in `remote.py` have changed but the code didn't. We need to change the code in order to use the correct imports.

### PR DESCRIPTION
**Pull request by juliamagan**
|Related issue|
|---|
|Closes #2562 |

## Description

After the merge of #1496, remoted tests started failing on nightly runs. The imports in `remote.py` have changed but the code didn't. We need to change the code in order to use the correct imports.

We have fixed imports in `remote.py`, warnings about unverified HTTPs requests, and changed `restart_remoted` to `restart_wazuh`.

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-2562.remoted.tests.x86_64.rpm

**test_remoted**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8048287/R1-2564-centos-manager.tar.gz)  | [🟢   ](https://ci.wazuh.info/view/Tests/job/Test_integration/20527/)
|R2 | [🔴 ](https://github.com/wazuh/wazuh-qa/files/8048288/R2-2564-centos-manager.tar.gz)  | [🟢 ](https://ci.wazuh.info/view/Tests/job/Test_integration/20528/)
|R3 | [🔴 ](https://github.com/wazuh/wazuh-qa/files/8048290/R3-2564-centos-manager.tar.gz)  | [🟢  ](https://ci.wazuh.info/view/Tests/job/Test_integration/20529/)

***

- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :orange_circle:: Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

### CODE REVIEW

**Comment by Rebits** [comment]
### 11/02/2022

- `test_remoted/test_agent_communication/test_shared_configuration.py`: Fixed 95e6637
Replace callback
```
'#!-up file \w+ merged.mg
```
to
```
'#!-up file .+ merged.mg
```

**Comment by juliamagan** [comment]
## 14/02/2022

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-2562.remoted.tests.x86_64.rpm

**test_remoted**

|CentOS Manager| Local| Jenkins | Notes |
|:--:|:--:|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8061843/R1-centos-manager.zip) | 
|R2 | [🟢 ](https://github.com/wazuh/wazuh-qa/files/8061845/R2-centos-manager.zip)  | 
|R3 | [🟢 ](https://github.com/wazuh/wazuh-qa/files/8061846/R3-centos-manager.zip)  | 

***


- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :orange_circle:: Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Comment by Rebits** [comment]
## 14/02/2022

### Packages

| Version | Revision | Link |
|:--:|:--:|:--:|
| v4.4.0 | 40400 | https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-2562.remoted.tests.x86_64.rpm

**test_remoted**

|CentOS Manager| Local|  Notes |
|:--:|:--:|:--:|
|R1| [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8061972/R3-2562-fix-remoted.tar.gz) | 
|R2 |  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8061973/R2-2562-fix-remoted.tar.gz)
|R3 | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/8061974/R1-2562-fix-remoted.tar.gz)  | |


***



- :green_circle:: All pass
- :yellow_circle:: Some warnings
- :orange_circle:: Jenkins problem
- :red_circle:: Some errors/fails
- :large_blue_circle:: In progress

**Review by Rebits — APPROVED** [review]
LGTM

**Review by snaow — APPROVED** [review]

**Pull request merged**
