### PR TITLE
Fix Workload Benchmark Plots

### PR DESCRIPTION
**Pull request by rafabailon**
# Description

The data used to generate the plots are now obtained from the API. Because of this, the plots are not being generated correctly, as the data and column names have changed.

Related to https://github.com/wazuh/wazuh-jenkins/issues/6203

---

## Testing performed

| OS | Package used |
| -- | -- |
| Debian 10 | Manager |

| Validation | Jenkins |
| --- | --- |
| The pipeline execution ends correctly | 🟢  |
| Check that the plots have been generated | 🟢 |

Build:

### CODE REVIEW

**Comment by rafabailon** [comment]
## Update

I have created a copy of the pipeline for testing purposes. In the default values, I have left all the necessary values checked so that, with a single run, the results of all the changes can be seen.

https://ci.wazuh.info/view/Tests_DEV/job/CLUSTER-Workload_benchmarks_metrics_6203/

I am reviewing the rest of the code to see if there is anything else to adapt to avoid, as much as possible, having to run several tests.

**Comment by rafabailon** [comment]
## Update

In the file `deps/wazuh_testing/wazuh_testing/tools/performance/statistic_headers.py` is the list of all the columns that are received from the API. I have checked and compared the data in that file with the data used to generate the plots.

**Comment by rafabailon** [comment]
## Update

After running the pipeline https://ci.wazuh.info/view/Tests_DEV/job/CLUSTER-Workload_benchmarks_metrics_6203/1/ it seems that the logcollector plots appear but the rest of the folders are still empty. Further investigation is necessary.

**Comment by rafabailon** [comment]
### Results

Build: https://ci.wazuh.info/view/Tests_DEV/job/CLUSTER-Workload_benchmarks_metrics_6203/8/

**Comment by rafabailon** [comment]
## Results

All plots are generated correctly

Build: https://ci.wazuh.info/view/Tests_DEV/job/CLUSTER-Workload_benchmarks_metrics_6203/13/

**Review by santipadilla — APPROVED** [review]

**Review by juliamagan — DISMISSED** [review]

**Review by juliamagan — DISMISSED** [review]

**Review by juliamagan — APPROVED** [review]

**Pull request merged**
