### PR TITLE
Added userData for AWS deployments

### PR DESCRIPTION
**Pull request by c-bordon**
close https://github.com/wazuh/wazuh-qa/issues/4988

The script is necessary to execute `userData` is added when launching the instances on `AWS`, since the security groups used in the `wazuh-dev` and `wazuh-qa` accounts have restricted port 22 since `AWS` public networks suffer attacks on these public ports. This script is responsible for configuring the `SSH` port of all supported OSes on port 2200

The test results are in the comments of this PR

### CODE REVIEW

**Comment by c-bordon** [comment]
## Tests

### Vagrant

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-debian-9-amd64 --provider vagrant --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 10:14:08] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 10:14:08] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 10:14:08] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 10:14:11] [DEBUG] ALLOCATOR: Vagrantfile created. Creating instance.
[2024-02-26 10:14:11] [INFO] ALLOCATOR: Instance VAGRANT-A0BF0223-368F-4033-B1D6-09DAEEBEDCB0 created.
[2024-02-26 10:16:36] [INFO] ALLOCATOR: Instance VAGRANT-A0BF0223-368F-4033-B1D6-09DAEEBEDCB0 started.
[2024-02-26 10:16:39] [DEBUG] ALLOCATOR: Using provided credentials
[2024-02-26 10:16:39] [INFO] ALLOCATOR: SSH connection string: ssh vagrant@192.168.57.3 -p 22 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 10:16:39] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 10:16:42] [DEBUG] ALLOCATOR: Using provided credentials
[2024-02-26 10:16:42] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
```

**Comment by c-bordon** [comment]
## AWS

### Ubuntu

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-ubuntu-22.04-amd64 --provider vagrant --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 10:12:20] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 10:12:20] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 10:12:20] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 10:12:23] [DEBUG] ALLOCATOR: Vagrantfile created. Creating instance.
[2024-02-26 10:12:23] [INFO] ALLOCATOR: Instance VAGRANT-F698B2EA-464B-4E00-902B-B71BC61412FE created.
[2024-02-26 10:13:04] [INFO] ALLOCATOR: Instance VAGRANT-F698B2EA-464B-4E00-902B-B71BC61412FE started.
[2024-02-26 10:13:07] [DEBUG] ALLOCATOR: Using provided credentials
[2024-02-26 10:13:07] [INFO] ALLOCATOR: SSH connection string: ssh vagrant@192.168.57.2 -p 22 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 10:13:07] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 10:13:09] [DEBUG] ALLOCATOR: Using provided credentials
[2024-02-26 10:13:09] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
```

**Comment by c-bordon** [comment]
### Debian

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-debian-10-amd64 --provider aws --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 10:17:31] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 10:17:31] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 10:17:31] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 10:17:32] [DEBUG] ALLOCATOR: Creating temp directory: /tmp/wazuh-qa/AWS-C11F2BE2-F824-4365-B924-B49E6FFBCE76
[2024-02-26 10:17:51] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-C11F2BE2-F824-4365-B924-B49E6FFBCE76 directory to /tmp/wazuh-qa/i-0f1bb23e1f47ba6b7
[2024-02-26 10:17:51] [INFO] ALLOCATOR: Instance i-0f1bb23e1f47ba6b7 created.
[2024-02-26 10:17:52] [INFO] ALLOCATOR: Instance i-0f1bb23e1f47ba6b7 started.
[2024-02-26 10:17:53] [INFO] ALLOCATOR: SSH connection string: ssh admin@ec2-44-192-107-153.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 10:17:53] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 10:17:53] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ ssh admin@ec2-44-192-107-153.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
The authenticity of host '[ec2-44-192-107-153.compute-1.amazonaws.com]:2200 ([44.192.107.153]:2200)' can't be established.
ED25519 key fingerprint is SHA256:saVA9IT8mmZgwellHuywdEvjApquLgah6SXv3oPZRO4.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes 
Warning: Permanently added '[ec2-44-192-107-153.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
Linux ip-172-31-14-169 4.19.0-25-cloud-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
admin@ip-172-31-14-169:~$ exit
```

**Comment by c-bordon** [comment]
### Oracle

```console
bordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-oracle-7-amd64 --provider aws --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 10:27:47] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 10:27:47] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 10:27:47] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 10:27:48] [DEBUG] ALLOCATOR: Creating temp directory: /tmp/wazuh-qa/AWS-3189E080-96AE-426E-8DA5-AA86B0358AA1
[2024-02-26 10:28:07] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-3189E080-96AE-426E-8DA5-AA86B0358AA1 directory to /tmp/wazuh-qa/i-0ef287f1c88f6e7d6
[2024-02-26 10:28:07] [INFO] ALLOCATOR: Instance i-0ef287f1c88f6e7d6 created.
[2024-02-26 10:28:08] [INFO] ALLOCATOR: Instance i-0ef287f1c88f6e7d6 started.
[2024-02-26 10:28:09] [INFO] ALLOCATOR: SSH connection string: ssh ec2-user@ec2-34-206-72-23.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 10:28:09] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 10:28:09] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ ssh ec2-user@ec2-34-206-72-23.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
The authenticity of host '[ec2-34-206-72-23.compute-1.amazonaws.com]:2200 ([34.206.72.23]:2200)' can't be established.
ED25519 key fingerprint is SHA256:5XdkBS2LUBY0mOJXnYtoSSpTHCTH9AAWPKRwCiwi+rk.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ec2-34-206-72-23.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
[ec2-user@ip-172-31-6-94 ~]$ exit
logout
Connection to ec2-34-206-72-23.compute-1.amazonaws.com closed.
```

**Comment by c-bordon** [comment]
### Amazon Linux

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-amazon-2-amd64 --provider aws --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 11:22:36] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 11:22:36] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 11:22:36] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 11:22:37] [DEBUG] ALLOCATOR: Creating temp directory: /tmp/wazuh-qa/AWS-B5349AF0-E69D-4B17-ABA3-310FA6C3CC73
[2024-02-26 11:22:54] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-B5349AF0-E69D-4B17-ABA3-310FA6C3CC73 directory to /tmp/wazuh-qa/i-0d866e9dc9c5610bb
[2024-02-26 11:22:54] [INFO] ALLOCATOR: Instance i-0d866e9dc9c5610bb created.
[2024-02-26 11:22:56] [INFO] ALLOCATOR: Instance i-0d866e9dc9c5610bb started.
[2024-02-26 11:22:56] [INFO] ALLOCATOR: SSH connection string: ssh ec2-user@ec2-44-211-185-172.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 11:22:56] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 11:22:56] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ ssh ec2-user@ec2-44-211-185-172.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
The authenticity of host '[ec2-44-211-185-172.compute-1.amazonaws.com]:2200 ([44.211.185.172]:2200)' can't be established.
ED25519 key fingerprint is SHA256:pG/Li6AIQTTsctZVHafKqU9VeNHH0E0t8RCnVPTyZmY.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ec2-44-211-185-172.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
   ,     #_
   ~\_  ####_        Amazon Linux 2
  ~~  \_#####\
  ~~     \###|       AL2 End of Life is 2025-06-30.
  ~~       \#/ ___
   ~~       V~' '->
    ~~~         /    A newer version of Amazon Linux is available!
      ~~._.   _/
         _/ _/       Amazon Linux 2023, GA and supported until 2028-03-15.
       _/m/'           https://aws.amazon.com/linux/amazon-linux-2023/

27 package(s) needed for security, out of 40 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-31-12-202 ~]$ exit
logout
Connection to ec2-44-211-185-172.compute-1.amazonaws.com closed.
```

**Comment by c-bordon** [comment]
### Centos

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-centos-7-amd64 --provider aws --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 11:41:34] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 11:41:34] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 11:41:34] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 11:41:35] [DEBUG] ALLOCATOR: Creating temp directory: /tmp/wazuh-qa/AWS-861B0B26-8ACC-4903-B5DC-B71FCD697B2B
[2024-02-26 11:41:54] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-861B0B26-8ACC-4903-B5DC-B71FCD697B2B directory to /tmp/wazuh-qa/i-00c9c3811ba3521e3
[2024-02-26 11:41:54] [INFO] ALLOCATOR: Instance i-00c9c3811ba3521e3 created.
[2024-02-26 11:41:55] [INFO] ALLOCATOR: Instance i-00c9c3811ba3521e3 started.
[2024-02-26 11:41:56] [INFO] ALLOCATOR: SSH connection string: ssh centos@ec2-3-231-102-152.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 11:41:56] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 11:41:56] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ ssh centos@ec2-3-231-102-152.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
The authenticity of host '[ec2-3-231-102-152.compute-1.amazonaws.com]:2200 ([3.231.102.152]:2200)' can't be established.
ED25519 key fingerprint is SHA256:onWuim687Q3Oq4KtmpNuIB2n0JncVGzJgz/z1blb9MA.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ec2-3-231-102-152.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
[centos@ip-172-31-8-179 ~]$ exit
logout
Connection to ec2-3-231-102-152.compute-1.amazonaws.com closed.
```

**Comment by c-bordon** [comment]
### Red Hat

```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ python3 launchers/allocation.py --composite-name linux-redhat-8-amd64 --provider aws --size micro --ssh-key ~/.ssh/allocation_test --label-issue https://github.com/wazuh/wazuh-qa/issues/4988 --label-team devops --label-termination-date "2024-02-26 15:00:00"
[2024-02-26 11:47:40] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-02-26 11:47:41] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-02-26 11:47:41] [DEBUG] ALLOCATOR: Using provided key pair
[2024-02-26 11:47:41] [DEBUG] ALLOCATOR: Creating temp directory: /tmp/wazuh-qa/AWS-B7000354-0677-4C88-8B21-2DF5E9140A71
[2024-02-26 11:48:00] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-B7000354-0677-4C88-8B21-2DF5E9140A71 directory to /tmp/wazuh-qa/i-001af14dbd9f5f0c7
[2024-02-26 11:48:00] [INFO] ALLOCATOR: Instance i-001af14dbd9f5f0c7 created.
[2024-02-26 11:48:02] [INFO] ALLOCATOR: Instance i-001af14dbd9f5f0c7 started.
[2024-02-26 11:48:02] [INFO] ALLOCATOR: SSH connection string: ssh ec2-user@ec2-44-201-29-198.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
[2024-02-26 11:48:02] [INFO] ALLOCATOR: Inventory file generated at /tmp/wazuh-qa/inventory.yml
[2024-02-26 11:48:02] [INFO] ALLOCATOR: Track file generated at /tmp/wazuh-qa/track.yml
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-qa/deployability$ ssh ec2-user@ec2-44-201-29-198.compute-1.amazonaws.com -p 2200 -i /home/cbordon/.ssh/allocation_test
The authenticity of host '[ec2-44-201-29-198.compute-1.amazonaws.com]:2200 ([44.201.29.198]:2200)' can't be established.
ED25519 key fingerprint is SHA256:gzXxIrtAnpH1q9p/+oUo1V/8bOhgWH8xvkO3GKaCr4A.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ec2-44-201-29-198.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

[ec2-user@ip-172-31-1-241 ~]$ exit
logout
Connection to ec2-44-201-29-198.compute-1.amazonaws.com closed.
```

**Review by QU3B1M — APPROVED** [review]
LGTM!

**Review by fcaffieri — APPROVED** [review]

**Review by teddytpc1 — APPROVED** [review]

**Pull request merged**
